// Code generated by @asyncapi/modelina 5.10.1 from api/asyncapi.yaml. DO NOT EDIT.

package sdm

import (
	"encoding/json"
	"fmt"
	"time"
)

// CameraClipPreviewEvent Clip preview URL associated with related events by eventSessionId. No inner eventId is required.
type CameraClipPreviewEvent struct {
	// EventSessionId Identifier connecting related camera events and their clip previews.
	EventSessionId EventSessionID `json:"eventSessionId"`
	// PreviewUrl The previewUrl value.
	PreviewUrl string `json:"previewUrl"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *CameraClipPreviewEvent) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("CameraClipPreviewEvent: expected an object")
	}
	if value, present := properties["eventSessionId"]; !present || string(value) == "null" {
		return fmt.Errorf("CameraClipPreviewEvent: required field %s is missing or null", "eventSessionId")
	}
	if value, present := properties["previewUrl"]; !present || string(value) == "null" {
		return fmt.Errorf("CameraClipPreviewEvent: required field %s is missing or null", "previewUrl")
	}
	if value, present := properties["eventSessionId"]; present && string(value) == "null" {
		return fmt.Errorf("CameraClipPreviewEvent: field %s cannot be null", "eventSessionId")
	}
	if value, present := properties["previewUrl"]; present && string(value) == "null" {
		return fmt.Errorf("CameraClipPreviewEvent: field %s cannot be null", "previewUrl")
	}

	type known CameraClipPreviewEvent
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "eventSessionId")
	delete(properties, "previewUrl")
	decoded.AdditionalProperties = properties
	*value = CameraClipPreviewEvent(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value CameraClipPreviewEvent) MarshalJSON() ([]byte, error) {
	type known CameraClipPreviewEvent
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "eventSessionId")
	delete(properties, "previewUrl")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// CameraEventID Camera image event identifier accepted by GenerateImage; distinct from the outer SDM event identifier.
type CameraEventID string

// CameraEvents Fully qualified event keys; future event payloads are retained.
type CameraEvents struct {
	// CameraMotion Motion detected. Event session and image event identifiers depend on the device family.
	CameraMotion *CameraMotionEvent `json:"sdm.devices.events.CameraMotion.Motion,omitempty"`
	// CameraPerson Person detected. Event session and image event identifiers depend on the device family.
	CameraPerson *CameraPersonEvent `json:"sdm.devices.events.CameraPerson.Person,omitempty"`
	// CameraSound Sound detected by the camera.
	CameraSound *CameraSoundEvent `json:"sdm.devices.events.CameraSound.Sound,omitempty"`
	// CameraClipPreview Clip preview URL associated with related events by eventSessionId. No inner eventId is required.
	CameraClipPreview *CameraClipPreviewEvent `json:"sdm.devices.events.CameraClipPreview.ClipPreview,omitempty"`
	// DoorbellChime Doorbell pressed. Session and image identifiers depend on the device family.
	DoorbellChime *DoorbellChimeEvent `json:"sdm.devices.events.DoorbellChime.Chime,omitempty"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *CameraEvents) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("CameraEvents: expected an object")
	}

	if value, present := properties["sdm.devices.events.CameraMotion.Motion"]; present && string(value) == "null" {
		return fmt.Errorf("CameraEvents: field %s cannot be null", "sdm.devices.events.CameraMotion.Motion")
	}
	if value, present := properties["sdm.devices.events.CameraPerson.Person"]; present && string(value) == "null" {
		return fmt.Errorf("CameraEvents: field %s cannot be null", "sdm.devices.events.CameraPerson.Person")
	}
	if value, present := properties["sdm.devices.events.CameraSound.Sound"]; present && string(value) == "null" {
		return fmt.Errorf("CameraEvents: field %s cannot be null", "sdm.devices.events.CameraSound.Sound")
	}
	if value, present := properties["sdm.devices.events.CameraClipPreview.ClipPreview"]; present && string(value) == "null" {
		return fmt.Errorf("CameraEvents: field %s cannot be null", "sdm.devices.events.CameraClipPreview.ClipPreview")
	}
	if value, present := properties["sdm.devices.events.DoorbellChime.Chime"]; present && string(value) == "null" {
		return fmt.Errorf("CameraEvents: field %s cannot be null", "sdm.devices.events.DoorbellChime.Chime")
	}

	type known CameraEvents
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "sdm.devices.events.CameraMotion.Motion")
	delete(properties, "sdm.devices.events.CameraPerson.Person")
	delete(properties, "sdm.devices.events.CameraSound.Sound")
	delete(properties, "sdm.devices.events.CameraClipPreview.ClipPreview")
	delete(properties, "sdm.devices.events.DoorbellChime.Chime")
	decoded.AdditionalProperties = properties
	*value = CameraEvents(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value CameraEvents) MarshalJSON() ([]byte, error) {
	type known CameraEvents
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "sdm.devices.events.CameraMotion.Motion")
	delete(properties, "sdm.devices.events.CameraPerson.Person")
	delete(properties, "sdm.devices.events.CameraSound.Sound")
	delete(properties, "sdm.devices.events.CameraClipPreview.ClipPreview")
	delete(properties, "sdm.devices.events.DoorbellChime.Chime")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// CameraMotionEvent Motion detected. Event session and image event identifiers depend on the device family.
type CameraMotionEvent struct {
	// EventId Camera image event identifier accepted by GenerateImage; distinct from the outer SDM event identifier.
	EventId *CameraEventID `json:"eventId,omitempty"`
	// EventSessionId Identifier connecting related camera events and their clip previews.
	EventSessionId *EventSessionID `json:"eventSessionId,omitempty"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *CameraMotionEvent) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("CameraMotionEvent: expected an object")
	}

	if value, present := properties["eventId"]; present && string(value) == "null" {
		return fmt.Errorf("CameraMotionEvent: field %s cannot be null", "eventId")
	}
	if value, present := properties["eventSessionId"]; present && string(value) == "null" {
		return fmt.Errorf("CameraMotionEvent: field %s cannot be null", "eventSessionId")
	}

	type known CameraMotionEvent
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	decoded.AdditionalProperties = properties
	*value = CameraMotionEvent(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value CameraMotionEvent) MarshalJSON() ([]byte, error) {
	type known CameraMotionEvent
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// CameraPersonEvent Person detected. Event session and image event identifiers depend on the device family.
type CameraPersonEvent struct {
	// EventId Camera image event identifier accepted by GenerateImage; distinct from the outer SDM event identifier.
	EventId *CameraEventID `json:"eventId,omitempty"`
	// EventSessionId Identifier connecting related camera events and their clip previews.
	EventSessionId *EventSessionID `json:"eventSessionId,omitempty"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *CameraPersonEvent) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("CameraPersonEvent: expected an object")
	}

	if value, present := properties["eventId"]; present && string(value) == "null" {
		return fmt.Errorf("CameraPersonEvent: field %s cannot be null", "eventId")
	}
	if value, present := properties["eventSessionId"]; present && string(value) == "null" {
		return fmt.Errorf("CameraPersonEvent: field %s cannot be null", "eventSessionId")
	}

	type known CameraPersonEvent
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	decoded.AdditionalProperties = properties
	*value = CameraPersonEvent(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value CameraPersonEvent) MarshalJSON() ([]byte, error) {
	type known CameraPersonEvent
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// CameraSoundEvent Sound detected by the camera.
type CameraSoundEvent struct {
	// EventId Camera image event identifier accepted by GenerateImage; distinct from the outer SDM event identifier.
	EventId *CameraEventID `json:"eventId,omitempty"`
	// EventSessionId Identifier connecting related camera events and their clip previews.
	EventSessionId *EventSessionID `json:"eventSessionId,omitempty"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *CameraSoundEvent) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("CameraSoundEvent: expected an object")
	}

	if value, present := properties["eventId"]; present && string(value) == "null" {
		return fmt.Errorf("CameraSoundEvent: field %s cannot be null", "eventId")
	}
	if value, present := properties["eventSessionId"]; present && string(value) == "null" {
		return fmt.Errorf("CameraSoundEvent: field %s cannot be null", "eventSessionId")
	}

	type known CameraSoundEvent
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	decoded.AdditionalProperties = properties
	*value = CameraSoundEvent(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value CameraSoundEvent) MarshalJSON() ([]byte, error) {
	type known CameraSoundEvent
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// DoorbellChimeEvent Doorbell pressed. Session and image identifiers depend on the device family.
type DoorbellChimeEvent struct {
	// EventId Camera image event identifier accepted by GenerateImage; distinct from the outer SDM event identifier.
	EventId *CameraEventID `json:"eventId,omitempty"`
	// EventSessionId Identifier connecting related camera events and their clip previews.
	EventSessionId *EventSessionID `json:"eventSessionId,omitempty"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *DoorbellChimeEvent) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("DoorbellChimeEvent: expected an object")
	}

	if value, present := properties["eventId"]; present && string(value) == "null" {
		return fmt.Errorf("DoorbellChimeEvent: field %s cannot be null", "eventId")
	}
	if value, present := properties["eventSessionId"]; present && string(value) == "null" {
		return fmt.Errorf("DoorbellChimeEvent: field %s cannot be null", "eventSessionId")
	}

	type known DoorbellChimeEvent
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	decoded.AdditionalProperties = properties
	*value = DoorbellChimeEvent(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value DoorbellChimeEvent) MarshalJSON() ([]byte, error) {
	type known DoorbellChimeEvent
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "eventId")
	delete(properties, "eventSessionId")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// EnvelopeEventID Unique outer SDM event identifier, distinct from camera image event identifiers.
type EnvelopeEventID string

// EventEnvelope SDM payload after decoding Pub/Sub message data. Outer event IDs differ from camera image event IDs.
type EventEnvelope struct {
	// EventId Unique outer SDM event identifier, distinct from camera image event identifiers.
	EventId EnvelopeEventID `json:"eventId"`
	// Timestamp Event occurrence time; receipt order may differ.
	Timestamp time.Time `json:"timestamp"`
	// UserId Obfuscated user identifier.
	UserId string `json:"userId"`
	// ResourceUpdate Typed trait changes and device action events for a resource.
	ResourceUpdate *ResourceUpdate `json:"resourceUpdate,omitempty"`
	// RelationUpdate A relation change. Subject may be empty when structure access is unavailable.
	RelationUpdate *ResourceRelation `json:"relationUpdate,omitempty"`
	// EventThreadId Identifier connecting updateable notifications, distinct from an event session.
	EventThreadId *EventThreadID `json:"eventThreadId,omitempty"`
	// EventThreadState Extensible thread state; known values are STARTED, UPDATED, ENDED.
	EventThreadState *EventThreadState `json:"eventThreadState,omitempty"`
	// ResourceGroup Resource names that may have related updates.
	ResourceGroup *[]string `json:"resourceGroup,omitempty"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *EventEnvelope) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("EventEnvelope: expected an object")
	}
	if value, present := properties["eventId"]; !present || string(value) == "null" {
		return fmt.Errorf("EventEnvelope: required field %s is missing or null", "eventId")
	}
	if value, present := properties["timestamp"]; !present || string(value) == "null" {
		return fmt.Errorf("EventEnvelope: required field %s is missing or null", "timestamp")
	}
	if value, present := properties["userId"]; !present || string(value) == "null" {
		return fmt.Errorf("EventEnvelope: required field %s is missing or null", "userId")
	}
	if value, present := properties["eventId"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "eventId")
	}
	if value, present := properties["timestamp"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "timestamp")
	}
	if value, present := properties["userId"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "userId")
	}
	if value, present := properties["resourceUpdate"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "resourceUpdate")
	}
	if value, present := properties["relationUpdate"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "relationUpdate")
	}
	if value, present := properties["eventThreadId"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "eventThreadId")
	}
	if value, present := properties["eventThreadState"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "eventThreadState")
	}
	if value, present := properties["resourceGroup"]; present && string(value) == "null" {
		return fmt.Errorf("EventEnvelope: field %s cannot be null", "resourceGroup")
	}
	if !((len(properties["resourceUpdate"]) != 0) || (len(properties["relationUpdate"]) != 0)) {
		return fmt.Errorf("EventEnvelope: missing required update variant")
	}
	type known EventEnvelope
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "eventId")
	delete(properties, "timestamp")
	delete(properties, "userId")
	delete(properties, "resourceUpdate")
	delete(properties, "relationUpdate")
	delete(properties, "eventThreadId")
	delete(properties, "eventThreadState")
	delete(properties, "resourceGroup")
	decoded.AdditionalProperties = properties
	*value = EventEnvelope(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value EventEnvelope) MarshalJSON() ([]byte, error) {
	type known EventEnvelope
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "eventId")
	delete(properties, "timestamp")
	delete(properties, "userId")
	delete(properties, "resourceUpdate")
	delete(properties, "relationUpdate")
	delete(properties, "eventThreadId")
	delete(properties, "eventThreadState")
	delete(properties, "resourceGroup")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// EventSessionID Identifier connecting related camera events and their clip previews.
type EventSessionID string

// EventThreadID Identifier connecting updateable notifications, distinct from an event session.
type EventThreadID string

// EventThreadState is an extensible protocol string.
type EventThreadState string

const (
	// EventThreadStateSTARTED is the STARTED value.
	EventThreadStateSTARTED EventThreadState = "STARTED"
	// EventThreadStateUPDATED is the UPDATED value.
	EventThreadStateUPDATED EventThreadState = "UPDATED"
	// EventThreadStateENDED is the ENDED value.
	EventThreadStateENDED EventThreadState = "ENDED"
)

// RelationType is an extensible protocol string.
type RelationType string

const (
	// RelationTypeCREATED is the CREATED value.
	RelationTypeCREATED RelationType = "CREATED"
	// RelationTypeUPDATED is the UPDATED value.
	RelationTypeUPDATED RelationType = "UPDATED"
	// RelationTypeDELETED is the DELETED value.
	RelationTypeDELETED RelationType = "DELETED"
)

// ResourceRelation A relation change. Subject may be empty when structure access is unavailable.
type ResourceRelation struct {
	// Type Extensible relation state; known values are CREATED, UPDATED, DELETED.
	Type RelationType `json:"type"`
	// Subject The subject value.
	Subject string `json:"subject"`
	// Object The object value.
	Object string `json:"object"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *ResourceRelation) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("ResourceRelation: expected an object")
	}
	if value, present := properties["type"]; !present || string(value) == "null" {
		return fmt.Errorf("ResourceRelation: required field %s is missing or null", "type")
	}
	if value, present := properties["subject"]; !present || string(value) == "null" {
		return fmt.Errorf("ResourceRelation: required field %s is missing or null", "subject")
	}
	if value, present := properties["object"]; !present || string(value) == "null" {
		return fmt.Errorf("ResourceRelation: required field %s is missing or null", "object")
	}
	if value, present := properties["type"]; present && string(value) == "null" {
		return fmt.Errorf("ResourceRelation: field %s cannot be null", "type")
	}
	if value, present := properties["subject"]; present && string(value) == "null" {
		return fmt.Errorf("ResourceRelation: field %s cannot be null", "subject")
	}
	if value, present := properties["object"]; present && string(value) == "null" {
		return fmt.Errorf("ResourceRelation: field %s cannot be null", "object")
	}

	type known ResourceRelation
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "type")
	delete(properties, "subject")
	delete(properties, "object")
	decoded.AdditionalProperties = properties
	*value = ResourceRelation(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value ResourceRelation) MarshalJSON() ([]byte, error) {
	type known ResourceRelation
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "type")
	delete(properties, "subject")
	delete(properties, "object")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}

// ResourceUpdate Typed trait changes and device action events for a resource.
type ResourceUpdate struct {
	// Name The name value.
	Name string `json:"name"`
	// Traits The traits value.
	Traits *Traits `json:"traits,omitempty"`
	// Events Fully qualified event keys; future event payloads are retained.
	Events *CameraEvents `json:"events,omitempty"`
	// AdditionalProperties retains unrecognized JSON fields.
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// UnmarshalJSON decodes known fields and preserves future server fields.
func (value *ResourceUpdate) UnmarshalJSON(data []byte) error {
	var properties map[string]json.RawMessage
	if err := json.Unmarshal(data, &properties); err != nil {
		return err
	}
	if properties == nil {
		return fmt.Errorf("ResourceUpdate: expected an object")
	}
	if value, present := properties["name"]; !present || string(value) == "null" {
		return fmt.Errorf("ResourceUpdate: required field %s is missing or null", "name")
	}
	if value, present := properties["name"]; present && string(value) == "null" {
		return fmt.Errorf("ResourceUpdate: field %s cannot be null", "name")
	}
	if value, present := properties["traits"]; present && string(value) == "null" {
		return fmt.Errorf("ResourceUpdate: field %s cannot be null", "traits")
	}
	if value, present := properties["events"]; present && string(value) == "null" {
		return fmt.Errorf("ResourceUpdate: field %s cannot be null", "events")
	}

	type known ResourceUpdate
	var decoded known
	if err := json.Unmarshal(data, &decoded); err != nil {
		return err
	}
	delete(properties, "name")
	delete(properties, "traits")
	delete(properties, "events")
	decoded.AdditionalProperties = properties
	*value = ResourceUpdate(decoded)
	return nil
}

// MarshalJSON combines typed fields with preserved future server fields.
func (value ResourceUpdate) MarshalJSON() ([]byte, error) {
	type known ResourceUpdate
	data, err := json.Marshal(known(value))
	if err != nil {
		return nil, err
	}
	properties := make(map[string]json.RawMessage, len(value.AdditionalProperties))
	for key, raw := range value.AdditionalProperties {
		properties[key] = raw
	}
	delete(properties, "name")
	delete(properties, "traits")
	delete(properties, "events")
	var typed map[string]json.RawMessage
	if err := json.Unmarshal(data, &typed); err != nil {
		return nil, err
	}
	for key, raw := range typed {
		properties[key] = raw
	}
	return json.Marshal(properties)
}
