// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.

package sdm

// DownloadClipPreviewRequest defines model for DownloadClipPreviewRequest.
type DownloadClipPreviewRequest struct {
	Auth AuthContext `json:"auth"`

	// URL Trusted previewUrl from a ClipPreview event; provider chooses the host, path and query.
	URL string `json:"url"`
}

// DownloadImageRequest defines model for DownloadImageRequest.
type DownloadImageRequest struct {
	// Auth Short-lived event image credentials from GenerateImage; distinct from OAuth credentials.
	Auth ImageAuthContext `json:"auth"`

	// Height Requested pixel height; the provider scales width when width is absent.
	Height *int `json:"height,omitempty"`

	// URL Trusted URL returned by GenerateImage; provider determines the host and opaque image identifier.
	URL string `json:"url"`

	// Width Requested pixel width; the provider scales height. Width takes precedence if both dimensions are supplied.
	Width *int `json:"width,omitempty"`
}

// ImageAuthContext Short-lived event image credentials from GenerateImage; distinct from OAuth credentials.
type ImageAuthContext struct {
	EventToken string `json:"eventToken"`
}
