// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.

package sdm

// ProviderError Sanitized provider failure cause available through errors.As. HTTPStatus identifies the received status; Code identifies the machine-readable provider rejection.
type ProviderError struct {
	// Code Sanitized machine-readable provider code. Free-form descriptions and token-bearing raw response bodies are never stored here.
	Code ProviderErrorCode `json:"code"`

	// HTTPStatus HTTP response status; zero if unavailable.
	HTTPStatus int `json:"httpStatus"`
}

// ProviderErrorCode Sanitized machine-readable provider code. Free-form descriptions and token-bearing raw response bodies are never stored here.
type ProviderErrorCode string
