// Package sdm provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package sdm

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for ReconcileDisposition.
const (
	ReconcileApplied     ReconcileDisposition = "APPLIED"
	ReconcileDuplicate   ReconcileDisposition = "DUPLICATE"
	ReconcileStale       ReconcileDisposition = "STALE"
	ReconcileUnrelated   ReconcileDisposition = "UNRELATED"
	ReconcileUnsupported ReconcileDisposition = "UNSUPPORTED"
)

// AckDeadlineRequest defines model for AckDeadlineRequest.
type AckDeadlineRequest struct {
	Seconds int `json:"seconds"`
}

// AuthContext defines model for AuthContext.
type AuthContext struct {
	AccessToken string `json:"accessToken"`
}

// CheckCommandRequest defines model for CheckCommandRequest.
type CheckCommandRequest struct {
	Command CommandName `json:"command"`
	Device  Device      `json:"device"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	AccessToken  string  `json:"accessToken"`
	ExpiresIn    int     `json:"expiresIn"`
	RefreshToken *string `json:"refreshToken,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	TokenType    string  `json:"tokenType"`
}

// DecodePushEventRequest defines model for DecodePushEventRequest.
type DecodePushEventRequest struct {
	Body      []byte `json:"body"`
	Unwrapped bool   `json:"unwrapped"`
}

// DecodePushEventResult defines model for DecodePushEventResult.
type DecodePushEventResult struct {
	// Event SDM payload after decoding Pub/Sub message data. Outer event IDs differ from camera image event IDs.
	Event EventEnvelope `json:"event"`
}

// Device defines model for Device.
type Device struct {
	Name            string            `json:"name"`
	ParentRelations *[]ParentRelation `json:"parentRelations,omitempty"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits *Traits `json:"traits,omitempty"`

	// Type Open device category; capabilities come from returned traits.
	Type                 *DeviceType                `json:"type,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// DeviceState defines model for DeviceState.
type DeviceState struct {
	Deleted        bool              `json:"deleted"`
	Device         Device            `json:"device"`
	RecentEventIds []EnvelopeEventID `json:"recentEventIds"`
	UpdatedAt      time.Time         `json:"updatedAt"`
	UserId         *string           `json:"userId,omitempty"`
}

// DeviceType Open device category; capabilities come from returned traits.
type DeviceType string

// ExchangeTokenRequest defines model for ExchangeTokenRequest.
type ExchangeTokenRequest struct {
	ClientId     string  `json:"clientId"`
	ClientSecret string  `json:"clientSecret"`
	Code         string  `json:"code"`
	CodeVerifier *string `json:"codeVerifier,omitempty"`
	RedirectUri  string  `json:"redirectUri"`
}

// ExchangeTokenResult defines model for ExchangeTokenResult.
type ExchangeTokenResult struct {
	Credentials Credentials `json:"credentials"`
}

// ExtendRtspStreamRequest defines model for ExtendRtspStreamRequest.
type ExtendRtspStreamRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for CameraLiveStream.ExtendRtspStream.
	Params CameraLiveStreamExtendRtspStreamParams `json:"params"`
}

// ExtendRtspStreamResult defines model for ExtendRtspStreamResult.
type ExtendRtspStreamResult struct {
	// Results Acknowledgement result for CameraLiveStream.ExtendRtspStream; physical action may complete later.
	Results CameraLiveStreamExtendRtspStreamResults `json:"results"`
}

// ExtendWebRtcStreamRequest defines model for ExtendWebRtcStreamRequest.
type ExtendWebRtcStreamRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for CameraLiveStream.ExtendWebRtcStream.
	Params CameraLiveStreamExtendWebRtcStreamParams `json:"params"`
}

// ExtendWebRtcStreamResult defines model for ExtendWebRtcStreamResult.
type ExtendWebRtcStreamResult struct {
	// Results Acknowledgement result for CameraLiveStream.ExtendWebRtcStream; physical action may complete later.
	Results CameraLiveStreamExtendWebRtcStreamResults `json:"results"`
}

// GenerateImageRequest defines model for GenerateImageRequest.
type GenerateImageRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for CameraEventImage.GenerateImage.
	Params CameraEventImageGenerateImageParams `json:"params"`
}

// GenerateImageResult defines model for GenerateImageResult.
type GenerateImageResult struct {
	// Results Acknowledgement result for CameraEventImage.GenerateImage; physical action may complete later.
	Results CameraEventImageGenerateImageResults `json:"results"`
}

// GenerateRtspStreamRequest defines model for GenerateRtspStreamRequest.
type GenerateRtspStreamRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for CameraLiveStream.GenerateRtspStream.
	Params CameraLiveStreamGenerateRtspStreamParams `json:"params"`
}

// GenerateRtspStreamResult defines model for GenerateRtspStreamResult.
type GenerateRtspStreamResult struct {
	// Results Acknowledgement result for CameraLiveStream.GenerateRtspStream; physical action may complete later.
	Results CameraLiveStreamGenerateRtspStreamResults `json:"results"`
}

// GenerateWebRtcStreamRequest defines model for GenerateWebRtcStreamRequest.
type GenerateWebRtcStreamRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for CameraLiveStream.GenerateWebRtcStream.
	Params CameraLiveStreamGenerateWebRtcStreamParams `json:"params"`
}

// GenerateWebRtcStreamResult defines model for GenerateWebRtcStreamResult.
type GenerateWebRtcStreamResult struct {
	// Results Acknowledgement result for CameraLiveStream.GenerateWebRtcStream; physical action may complete later.
	Results CameraLiveStreamGenerateWebRtcStreamResults `json:"results"`
}

// GetDeviceRequest defines model for GetDeviceRequest.
type GetDeviceRequest struct {
	Auth AuthContext `json:"auth"`
	Name string      `json:"name"`
}

// GetDeviceResult defines model for GetDeviceResult.
type GetDeviceResult struct {
	Device Device `json:"device"`
}

// GetRoomRequest defines model for GetRoomRequest.
type GetRoomRequest struct {
	Auth AuthContext `json:"auth"`
	Name string      `json:"name"`
}

// GetRoomResult defines model for GetRoomResult.
type GetRoomResult struct {
	Room Room `json:"room"`
}

// GetStructureRequest defines model for GetStructureRequest.
type GetStructureRequest struct {
	Auth AuthContext `json:"auth"`
	Name string      `json:"name"`
}

// GetStructureResult defines model for GetStructureResult.
type GetStructureResult struct {
	Structure Structure `json:"structure"`
}

// HandleEventRequest defines model for HandleEventRequest.
type HandleEventRequest struct {
	Data []byte `json:"data"`
}

// HandleEventResult defines model for HandleEventResult.
type HandleEventResult struct {
	// Event SDM payload after decoding Pub/Sub message data. Outer event IDs differ from camera image event IDs.
	Event EventEnvelope `json:"event"`
}

// ListDevicesRequest defines model for ListDevicesRequest.
type ListDevicesRequest struct {
	Auth   AuthContext `json:"auth"`
	Filter *string     `json:"filter,omitempty"`
	Parent string      `json:"parent"`
}

// ListDevicesResult defines model for ListDevicesResult.
type ListDevicesResult struct {
	Devices []Device `json:"devices"`
}

// ListRoomsRequest defines model for ListRoomsRequest.
type ListRoomsRequest struct {
	Auth   AuthContext `json:"auth"`
	Parent string      `json:"parent"`
}

// ListRoomsResult defines model for ListRoomsResult.
type ListRoomsResult struct {
	Rooms []Room `json:"rooms"`
}

// ListStructuresRequest defines model for ListStructuresRequest.
type ListStructuresRequest struct {
	Auth   AuthContext `json:"auth"`
	Parent string      `json:"parent"`
}

// ListStructuresResult defines model for ListStructuresResult.
type ListStructuresResult struct {
	Structures []Structure `json:"structures"`
}

// OpenEventSessionRequest defines model for OpenEventSessionRequest.
type OpenEventSessionRequest struct {
	Auth         AuthContext `json:"auth"`
	MaxMessages  *int        `json:"maxMessages,omitempty"`
	Subscription string      `json:"subscription"`
}

// ParentRelation defines model for ParentRelation.
type ParentRelation struct {
	DisplayName          *string                    `json:"displayName,omitempty"`
	Parent               *string                    `json:"parent,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ReconcileDisposition defines model for ReconcileDisposition.
type ReconcileDisposition string

// ReconcileRequest defines model for ReconcileRequest.
type ReconcileRequest struct {
	// Event SDM payload after decoding Pub/Sub message data. Outer event IDs differ from camera image event IDs.
	Event EventEnvelope `json:"event"`
	State DeviceState   `json:"state"`
}

// ReconcileResult defines model for ReconcileResult.
type ReconcileResult struct {
	Disposition ReconcileDisposition `json:"disposition"`
	State       DeviceState          `json:"state"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	ClientId     string `json:"clientId"`
	ClientSecret string `json:"clientSecret"`
	RefreshToken string `json:"refreshToken"`
}

// RefreshTokenResult defines model for RefreshTokenResult.
type RefreshTokenResult struct {
	Credentials Credentials `json:"credentials"`
}

// Room defines model for Room.
type Room struct {
	Name string `json:"name"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits               *Traits                    `json:"traits,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// SetCoolRequest defines model for SetCoolRequest.
type SetCoolRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for ThermostatTemperatureSetpoint.SetCool.
	Params ThermostatTemperatureSetpointSetCoolParams `json:"params"`
}

// SetCoolResult defines model for SetCoolResult.
type SetCoolResult struct {
	Results EmptyResults `json:"results"`
}

// SetFanTimerRequest defines model for SetFanTimerRequest.
type SetFanTimerRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for Fan.SetTimer.
	Params FanSetTimerParams `json:"params"`
}

// SetFanTimerResult defines model for SetFanTimerResult.
type SetFanTimerResult struct {
	Results EmptyResults `json:"results"`
}

// SetHeatRequest defines model for SetHeatRequest.
type SetHeatRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for ThermostatTemperatureSetpoint.SetHeat.
	Params ThermostatTemperatureSetpointSetHeatParams `json:"params"`
}

// SetHeatResult defines model for SetHeatResult.
type SetHeatResult struct {
	Results EmptyResults `json:"results"`
}

// SetRangeRequest defines model for SetRangeRequest.
type SetRangeRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for ThermostatTemperatureSetpoint.SetRange.
	Params ThermostatTemperatureSetpointSetRangeParams `json:"params"`
}

// SetRangeResult defines model for SetRangeResult.
type SetRangeResult struct {
	Results EmptyResults `json:"results"`
}

// SetThermostatEcoModeRequest defines model for SetThermostatEcoModeRequest.
type SetThermostatEcoModeRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for ThermostatEco.SetMode.
	Params ThermostatEcoSetModeParams `json:"params"`
}

// SetThermostatEcoModeResult defines model for SetThermostatEcoModeResult.
type SetThermostatEcoModeResult struct {
	Results EmptyResults `json:"results"`
}

// SetThermostatModeRequest defines model for SetThermostatModeRequest.
type SetThermostatModeRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for ThermostatMode.SetMode.
	Params ThermostatModeSetModeParams `json:"params"`
}

// SetThermostatModeResult defines model for SetThermostatModeResult.
type SetThermostatModeResult struct {
	Results EmptyResults `json:"results"`
}

// StopRtspStreamRequest defines model for StopRtspStreamRequest.
type StopRtspStreamRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for CameraLiveStream.StopRtspStream.
	Params CameraLiveStreamStopRtspStreamParams `json:"params"`
}

// StopRtspStreamResult defines model for StopRtspStreamResult.
type StopRtspStreamResult struct {
	Results EmptyResults `json:"results"`
}

// StopWebRtcStreamRequest defines model for StopWebRtcStreamRequest.
type StopWebRtcStreamRequest struct {
	Auth       AuthContext `json:"auth"`
	DeviceName string      `json:"deviceName"`

	// Params Inputs for CameraLiveStream.StopWebRtcStream.
	Params CameraLiveStreamStopWebRtcStreamParams `json:"params"`
}

// StopWebRtcStreamResult defines model for StopWebRtcStreamResult.
type StopWebRtcStreamResult struct {
	Results EmptyResults `json:"results"`
}

// Structure defines model for Structure.
type Structure struct {
	Name string `json:"name"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits               *Traits                    `json:"traits,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Getter for additional properties for Device. Returns the specified
// element and whether it was found
func (a Device) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Device
func (a *Device) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a *Device) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["parentRelations"]; found {
		err = json.Unmarshal(raw, &a.ParentRelations)
		if err != nil {
			return fmt.Errorf("error reading 'parentRelations': %w", err)
		}
		delete(object, "parentRelations")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a Device) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.ParentRelations != nil {
		object["parentRelations"], err = json.Marshal(a.ParentRelations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parentRelations': %w", err)
		}
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ParentRelation. Returns the specified
// element and whether it was found
func (a ParentRelation) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ParentRelation
func (a *ParentRelation) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ParentRelation to handle AdditionalProperties
func (a *ParentRelation) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["displayName"]; found {
		err = json.Unmarshal(raw, &a.DisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'displayName': %w", err)
		}
		delete(object, "displayName")
	}

	if raw, found := object["parent"]; found {
		err = json.Unmarshal(raw, &a.Parent)
		if err != nil {
			return fmt.Errorf("error reading 'parent': %w", err)
		}
		delete(object, "parent")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ParentRelation to handle AdditionalProperties
func (a ParentRelation) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DisplayName != nil {
		object["displayName"], err = json.Marshal(a.DisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'displayName': %w", err)
		}
	}

	if a.Parent != nil {
		object["parent"], err = json.Marshal(a.Parent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parent': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Room. Returns the specified
// element and whether it was found
func (a Room) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Room
func (a *Room) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Room to handle AdditionalProperties
func (a *Room) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Room to handle AdditionalProperties
func (a Room) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Structure. Returns the specified
// element and whether it was found
func (a Structure) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Structure
func (a *Structure) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Structure to handle AdditionalProperties
func (a *Structure) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Structure to handle AdditionalProperties
func (a Structure) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
