// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
	"time"
)

// Defines values for CommandName.
const (
	SdmDevicesCommandsCameraEventImageGenerateImage         CommandName = "sdm.devices.commands.CameraEventImage.GenerateImage"
	SdmDevicesCommandsCameraLiveStreamExtendRtspStream      CommandName = "sdm.devices.commands.CameraLiveStream.ExtendRtspStream"
	SdmDevicesCommandsCameraLiveStreamExtendWebRtcStream    CommandName = "sdm.devices.commands.CameraLiveStream.ExtendWebRtcStream"
	SdmDevicesCommandsCameraLiveStreamGenerateRtspStream    CommandName = "sdm.devices.commands.CameraLiveStream.GenerateRtspStream"
	SdmDevicesCommandsCameraLiveStreamGenerateWebRtcStream  CommandName = "sdm.devices.commands.CameraLiveStream.GenerateWebRtcStream"
	SdmDevicesCommandsCameraLiveStreamStopRtspStream        CommandName = "sdm.devices.commands.CameraLiveStream.StopRtspStream"
	SdmDevicesCommandsCameraLiveStreamStopWebRtcStream      CommandName = "sdm.devices.commands.CameraLiveStream.StopWebRtcStream"
	SdmDevicesCommandsFanSetTimer                           CommandName = "sdm.devices.commands.Fan.SetTimer"
	SdmDevicesCommandsThermostatEcoSetMode                  CommandName = "sdm.devices.commands.ThermostatEco.SetMode"
	SdmDevicesCommandsThermostatModeSetMode                 CommandName = "sdm.devices.commands.ThermostatMode.SetMode"
	SdmDevicesCommandsThermostatTemperatureSetpointSetCool  CommandName = "sdm.devices.commands.ThermostatTemperatureSetpoint.SetCool"
	SdmDevicesCommandsThermostatTemperatureSetpointSetHeat  CommandName = "sdm.devices.commands.ThermostatTemperatureSetpoint.SetHeat"
	SdmDevicesCommandsThermostatTemperatureSetpointSetRange CommandName = "sdm.devices.commands.ThermostatTemperatureSetpoint.SetRange"
)

// Defines values for FanSetTimerParamsTimerMode.
const (
	FanSetTimerParamsTimerModeOFF FanSetTimerParamsTimerMode = "OFF"
	FanSetTimerParamsTimerModeON  FanSetTimerParamsTimerMode = "ON"
)

// Defines values for ThermostatEcoSetModeParamsMode.
const (
	ThermostatEcoSetModeParamsModeMANUALECO ThermostatEcoSetModeParamsMode = "MANUAL_ECO"
	ThermostatEcoSetModeParamsModeOFF       ThermostatEcoSetModeParamsMode = "OFF"
)

// Defines values for ThermostatModeSetModeParamsMode.
const (
	COOL     ThermostatModeSetModeParamsMode = "COOL"
	HEAT     ThermostatModeSetModeParamsMode = "HEAT"
	HEATCOOL ThermostatModeSetModeParamsMode = "HEATCOOL"
	OFF      ThermostatModeSetModeParamsMode = "OFF"
)

// CameraEventImageGenerateImageParams Inputs for CameraEventImage.GenerateImage.
type CameraEventImageGenerateImageParams struct {
	EventId string `json:"eventId"`
}

// CameraEventImageGenerateImageResults Acknowledgement result for CameraEventImage.GenerateImage; physical action may complete later.
type CameraEventImageGenerateImageResults struct {
	Token                string                     `json:"token"`
	Url                  string                     `json:"url"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CameraLiveStreamExtendRtspStreamParams Inputs for CameraLiveStream.ExtendRtspStream.
type CameraLiveStreamExtendRtspStreamParams struct {
	StreamExtensionToken string `json:"streamExtensionToken"`
}

// CameraLiveStreamExtendRtspStreamResults Acknowledgement result for CameraLiveStream.ExtendRtspStream; physical action may complete later.
type CameraLiveStreamExtendRtspStreamResults struct {
	ExpiresAt            time.Time                  `json:"expiresAt"`
	StreamExtensionToken string                     `json:"streamExtensionToken"`
	StreamToken          string                     `json:"streamToken"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CameraLiveStreamExtendWebRtcStreamParams Inputs for CameraLiveStream.ExtendWebRtcStream.
type CameraLiveStreamExtendWebRtcStreamParams struct {
	MediaSessionId string `json:"mediaSessionId"`
}

// CameraLiveStreamExtendWebRtcStreamResults Acknowledgement result for CameraLiveStream.ExtendWebRtcStream; physical action may complete later.
type CameraLiveStreamExtendWebRtcStreamResults struct {
	ExpiresAt            time.Time                  `json:"expiresAt"`
	MediaSessionId       string                     `json:"mediaSessionId"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CameraLiveStreamGenerateRtspStreamParams Inputs for CameraLiveStream.GenerateRtspStream.
type CameraLiveStreamGenerateRtspStreamParams = struct{}

// CameraLiveStreamGenerateRtspStreamResults Acknowledgement result for CameraLiveStream.GenerateRtspStream; physical action may complete later.
type CameraLiveStreamGenerateRtspStreamResults struct {
	ExpiresAt            time.Time                  `json:"expiresAt"`
	StreamExtensionToken string                     `json:"streamExtensionToken"`
	StreamToken          string                     `json:"streamToken"`
	StreamUrls           RtspStreamURLs             `json:"streamUrls"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CameraLiveStreamGenerateWebRtcStreamParams Inputs for CameraLiveStream.GenerateWebRtcStream.
type CameraLiveStreamGenerateWebRtcStreamParams struct {
	OfferSdp string `json:"offerSdp"`
}

// CameraLiveStreamGenerateWebRtcStreamResults Acknowledgement result for CameraLiveStream.GenerateWebRtcStream; physical action may complete later.
type CameraLiveStreamGenerateWebRtcStreamResults struct {
	AnswerSdp            string                     `json:"answerSdp"`
	ExpiresAt            time.Time                  `json:"expiresAt"`
	MediaSessionId       string                     `json:"mediaSessionId"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CameraLiveStreamStopRtspStreamParams Inputs for CameraLiveStream.StopRtspStream.
type CameraLiveStreamStopRtspStreamParams struct {
	StreamExtensionToken string `json:"streamExtensionToken"`
}

// CameraLiveStreamStopRtspStreamResults Acknowledgement result for CameraLiveStream.StopRtspStream; physical action may complete later.
type CameraLiveStreamStopRtspStreamResults map[string]json.RawMessage

// CameraLiveStreamStopWebRtcStreamParams Inputs for CameraLiveStream.StopWebRtcStream.
type CameraLiveStreamStopWebRtcStreamParams struct {
	MediaSessionId string `json:"mediaSessionId"`
}

// CameraLiveStreamStopWebRtcStreamResults Acknowledgement result for CameraLiveStream.StopWebRtcStream; physical action may complete later.
type CameraLiveStreamStopWebRtcStreamResults map[string]json.RawMessage

// CommandName defines model for CommandName.
type CommandName string

// EmptyResults defines model for EmptyResults.
type EmptyResults map[string]json.RawMessage

// FanSetTimerParams Inputs for Fan.SetTimer.
type FanSetTimerParams struct {
	// Duration Optional fan duration from 1 through 43200 seconds, default 900 seconds.
	Duration  *string                    `json:"duration,omitempty"`
	TimerMode FanSetTimerParamsTimerMode `json:"timerMode"`
}

// FanSetTimerParamsTimerMode defines model for FanSetTimerParams.TimerMode.
type FanSetTimerParamsTimerMode string

// FanSetTimerResults Acknowledgement result for Fan.SetTimer; physical action may complete later.
type FanSetTimerResults map[string]json.RawMessage

// RtspStreamURLs defines model for RtspStreamURLs.
type RtspStreamURLs struct {
	RtspUrl              string                     `json:"rtspUrl"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ThermostatEcoSetModeParams Inputs for ThermostatEco.SetMode.
type ThermostatEcoSetModeParams struct {
	Mode ThermostatEcoSetModeParamsMode `json:"mode"`
}

// ThermostatEcoSetModeParamsMode defines model for ThermostatEcoSetModeParams.Mode.
type ThermostatEcoSetModeParamsMode string

// ThermostatEcoSetModeResults Acknowledgement result for ThermostatEco.SetMode; physical action may complete later.
type ThermostatEcoSetModeResults map[string]json.RawMessage

// ThermostatModeSetModeParams Inputs for ThermostatMode.SetMode.
type ThermostatModeSetModeParams struct {
	Mode ThermostatModeSetModeParamsMode `json:"mode"`
}

// ThermostatModeSetModeParamsMode defines model for ThermostatModeSetModeParams.Mode.
type ThermostatModeSetModeParamsMode string

// ThermostatModeSetModeResults Acknowledgement result for ThermostatMode.SetMode; physical action may complete later.
type ThermostatModeSetModeResults map[string]json.RawMessage

// ThermostatTemperatureSetpointSetCoolParams Inputs for ThermostatTemperatureSetpoint.SetCool.
type ThermostatTemperatureSetpointSetCoolParams struct {
	CoolCelsius float64 `json:"coolCelsius"`
}

// ThermostatTemperatureSetpointSetCoolResults Acknowledgement result for ThermostatTemperatureSetpoint.SetCool; physical action may complete later.
type ThermostatTemperatureSetpointSetCoolResults map[string]json.RawMessage

// ThermostatTemperatureSetpointSetHeatParams Inputs for ThermostatTemperatureSetpoint.SetHeat.
type ThermostatTemperatureSetpointSetHeatParams struct {
	HeatCelsius float64 `json:"heatCelsius"`
}

// ThermostatTemperatureSetpointSetHeatResults Acknowledgement result for ThermostatTemperatureSetpoint.SetHeat; physical action may complete later.
type ThermostatTemperatureSetpointSetHeatResults map[string]json.RawMessage

// ThermostatTemperatureSetpointSetRangeParams Inputs for ThermostatTemperatureSetpoint.SetRange.
type ThermostatTemperatureSetpointSetRangeParams struct {
	CoolCelsius float64 `json:"coolCelsius"`
	HeatCelsius float64 `json:"heatCelsius"`
}

// ThermostatTemperatureSetpointSetRangeResults Acknowledgement result for ThermostatTemperatureSetpoint.SetRange; physical action may complete later.
type ThermostatTemperatureSetpointSetRangeResults map[string]json.RawMessage

// Getter for additional properties for CameraEventImageGenerateImageResults. Returns the specified
// element and whether it was found
func (a CameraEventImageGenerateImageResults) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CameraEventImageGenerateImageResults
func (a *CameraEventImageGenerateImageResults) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CameraEventImageGenerateImageResults to handle AdditionalProperties
func (a *CameraEventImageGenerateImageResults) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["token"]; found {
		err = json.Unmarshal(raw, &a.Token)
		if err != nil {
			return fmt.Errorf("error reading 'token': %w", err)
		}
		delete(object, "token")
	}

	if raw, found := object["url"]; found {
		err = json.Unmarshal(raw, &a.Url)
		if err != nil {
			return fmt.Errorf("error reading 'url': %w", err)
		}
		delete(object, "url")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CameraEventImageGenerateImageResults to handle AdditionalProperties
func (a CameraEventImageGenerateImageResults) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["token"], err = json.Marshal(a.Token)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token': %w", err)
	}

	object["url"], err = json.Marshal(a.Url)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'url': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CameraLiveStreamExtendRtspStreamResults. Returns the specified
// element and whether it was found
func (a CameraLiveStreamExtendRtspStreamResults) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CameraLiveStreamExtendRtspStreamResults
func (a *CameraLiveStreamExtendRtspStreamResults) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CameraLiveStreamExtendRtspStreamResults to handle AdditionalProperties
func (a *CameraLiveStreamExtendRtspStreamResults) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["expiresAt"]; found {
		err = json.Unmarshal(raw, &a.ExpiresAt)
		if err != nil {
			return fmt.Errorf("error reading 'expiresAt': %w", err)
		}
		delete(object, "expiresAt")
	}

	if raw, found := object["streamExtensionToken"]; found {
		err = json.Unmarshal(raw, &a.StreamExtensionToken)
		if err != nil {
			return fmt.Errorf("error reading 'streamExtensionToken': %w", err)
		}
		delete(object, "streamExtensionToken")
	}

	if raw, found := object["streamToken"]; found {
		err = json.Unmarshal(raw, &a.StreamToken)
		if err != nil {
			return fmt.Errorf("error reading 'streamToken': %w", err)
		}
		delete(object, "streamToken")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CameraLiveStreamExtendRtspStreamResults to handle AdditionalProperties
func (a CameraLiveStreamExtendRtspStreamResults) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["expiresAt"], err = json.Marshal(a.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'expiresAt': %w", err)
	}

	object["streamExtensionToken"], err = json.Marshal(a.StreamExtensionToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'streamExtensionToken': %w", err)
	}

	object["streamToken"], err = json.Marshal(a.StreamToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'streamToken': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CameraLiveStreamExtendWebRtcStreamResults. Returns the specified
// element and whether it was found
func (a CameraLiveStreamExtendWebRtcStreamResults) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CameraLiveStreamExtendWebRtcStreamResults
func (a *CameraLiveStreamExtendWebRtcStreamResults) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CameraLiveStreamExtendWebRtcStreamResults to handle AdditionalProperties
func (a *CameraLiveStreamExtendWebRtcStreamResults) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["expiresAt"]; found {
		err = json.Unmarshal(raw, &a.ExpiresAt)
		if err != nil {
			return fmt.Errorf("error reading 'expiresAt': %w", err)
		}
		delete(object, "expiresAt")
	}

	if raw, found := object["mediaSessionId"]; found {
		err = json.Unmarshal(raw, &a.MediaSessionId)
		if err != nil {
			return fmt.Errorf("error reading 'mediaSessionId': %w", err)
		}
		delete(object, "mediaSessionId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CameraLiveStreamExtendWebRtcStreamResults to handle AdditionalProperties
func (a CameraLiveStreamExtendWebRtcStreamResults) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["expiresAt"], err = json.Marshal(a.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'expiresAt': %w", err)
	}

	object["mediaSessionId"], err = json.Marshal(a.MediaSessionId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mediaSessionId': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CameraLiveStreamGenerateRtspStreamResults. Returns the specified
// element and whether it was found
func (a CameraLiveStreamGenerateRtspStreamResults) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CameraLiveStreamGenerateRtspStreamResults
func (a *CameraLiveStreamGenerateRtspStreamResults) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CameraLiveStreamGenerateRtspStreamResults to handle AdditionalProperties
func (a *CameraLiveStreamGenerateRtspStreamResults) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["expiresAt"]; found {
		err = json.Unmarshal(raw, &a.ExpiresAt)
		if err != nil {
			return fmt.Errorf("error reading 'expiresAt': %w", err)
		}
		delete(object, "expiresAt")
	}

	if raw, found := object["streamExtensionToken"]; found {
		err = json.Unmarshal(raw, &a.StreamExtensionToken)
		if err != nil {
			return fmt.Errorf("error reading 'streamExtensionToken': %w", err)
		}
		delete(object, "streamExtensionToken")
	}

	if raw, found := object["streamToken"]; found {
		err = json.Unmarshal(raw, &a.StreamToken)
		if err != nil {
			return fmt.Errorf("error reading 'streamToken': %w", err)
		}
		delete(object, "streamToken")
	}

	if raw, found := object["streamUrls"]; found {
		err = json.Unmarshal(raw, &a.StreamUrls)
		if err != nil {
			return fmt.Errorf("error reading 'streamUrls': %w", err)
		}
		delete(object, "streamUrls")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CameraLiveStreamGenerateRtspStreamResults to handle AdditionalProperties
func (a CameraLiveStreamGenerateRtspStreamResults) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["expiresAt"], err = json.Marshal(a.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'expiresAt': %w", err)
	}

	object["streamExtensionToken"], err = json.Marshal(a.StreamExtensionToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'streamExtensionToken': %w", err)
	}

	object["streamToken"], err = json.Marshal(a.StreamToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'streamToken': %w", err)
	}

	object["streamUrls"], err = json.Marshal(a.StreamUrls)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'streamUrls': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CameraLiveStreamGenerateWebRtcStreamResults. Returns the specified
// element and whether it was found
func (a CameraLiveStreamGenerateWebRtcStreamResults) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CameraLiveStreamGenerateWebRtcStreamResults
func (a *CameraLiveStreamGenerateWebRtcStreamResults) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CameraLiveStreamGenerateWebRtcStreamResults to handle AdditionalProperties
func (a *CameraLiveStreamGenerateWebRtcStreamResults) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["answerSdp"]; found {
		err = json.Unmarshal(raw, &a.AnswerSdp)
		if err != nil {
			return fmt.Errorf("error reading 'answerSdp': %w", err)
		}
		delete(object, "answerSdp")
	}

	if raw, found := object["expiresAt"]; found {
		err = json.Unmarshal(raw, &a.ExpiresAt)
		if err != nil {
			return fmt.Errorf("error reading 'expiresAt': %w", err)
		}
		delete(object, "expiresAt")
	}

	if raw, found := object["mediaSessionId"]; found {
		err = json.Unmarshal(raw, &a.MediaSessionId)
		if err != nil {
			return fmt.Errorf("error reading 'mediaSessionId': %w", err)
		}
		delete(object, "mediaSessionId")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CameraLiveStreamGenerateWebRtcStreamResults to handle AdditionalProperties
func (a CameraLiveStreamGenerateWebRtcStreamResults) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["answerSdp"], err = json.Marshal(a.AnswerSdp)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'answerSdp': %w", err)
	}

	object["expiresAt"], err = json.Marshal(a.ExpiresAt)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'expiresAt': %w", err)
	}

	object["mediaSessionId"], err = json.Marshal(a.MediaSessionId)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'mediaSessionId': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RtspStreamURLs. Returns the specified
// element and whether it was found
func (a RtspStreamURLs) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RtspStreamURLs
func (a *RtspStreamURLs) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RtspStreamURLs to handle AdditionalProperties
func (a *RtspStreamURLs) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["rtspUrl"]; found {
		err = json.Unmarshal(raw, &a.RtspUrl)
		if err != nil {
			return fmt.Errorf("error reading 'rtspUrl': %w", err)
		}
		delete(object, "rtspUrl")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RtspStreamURLs to handle AdditionalProperties
func (a RtspStreamURLs) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["rtspUrl"], err = json.Marshal(a.RtspUrl)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'rtspUrl': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
