// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
)

// Device defines model for Device.
type Device struct {
	Assignee        *string           `json:"assignee,omitempty"`
	Name            string            `json:"name"`
	ParentRelations *[]ParentRelation `json:"parentRelations,omitempty"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits *Traits `json:"traits,omitempty"`

	// Type Informational device type; use traits to infer capabilities.
	Type                 *DeviceType                `json:"type,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// DeviceType Informational device type; use traits to infer capabilities.
type DeviceType string

// ExecuteCommandRequest defines model for ExecuteCommandRequest.
type ExecuteCommandRequest struct {
	Command CommandName     `json:"command"`
	Params  json.RawMessage `json:"params"`
}

// ExecuteCommandResponse defines model for ExecuteCommandResponse.
type ExecuteCommandResponse struct {
	Results              *json.RawMessage           `json:"results,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ListDevicesResponse defines model for ListDevicesResponse.
type ListDevicesResponse struct {
	Devices              *[]Device                  `json:"devices,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ListRoomsResponse defines model for ListRoomsResponse.
type ListRoomsResponse struct {
	Rooms                *[]Room                    `json:"rooms,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ListStructuresResponse defines model for ListStructuresResponse.
type ListStructuresResponse struct {
	Structures           *[]Structure               `json:"structures,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ParentRelation defines model for ParentRelation.
type ParentRelation struct {
	DisplayName          *string                    `json:"displayName,omitempty"`
	Parent               *string                    `json:"parent,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Room defines model for Room.
type Room struct {
	Name string `json:"name"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits               *Traits                    `json:"traits,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Structure defines model for Structure.
type Structure struct {
	Name string `json:"name"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits               *Traits                    `json:"traits,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ListDevicesParams defines parameters for ListDevices.
type ListDevicesParams struct {
	// Filter Requested device filter; service-defined expression.
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// ExecuteCommandJSONRequestBody defines body for ExecuteCommand for application/json ContentType.
type ExecuteCommandJSONRequestBody = ExecuteCommandRequest

// Getter for additional properties for Device. Returns the specified
// element and whether it was found
func (a Device) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Device
func (a *Device) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a *Device) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["assignee"]; found {
		err = json.Unmarshal(raw, &a.Assignee)
		if err != nil {
			return fmt.Errorf("error reading 'assignee': %w", err)
		}
		delete(object, "assignee")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["parentRelations"]; found {
		err = json.Unmarshal(raw, &a.ParentRelations)
		if err != nil {
			return fmt.Errorf("error reading 'parentRelations': %w", err)
		}
		delete(object, "parentRelations")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a Device) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Assignee != nil {
		object["assignee"], err = json.Marshal(a.Assignee)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'assignee': %w", err)
		}
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.ParentRelations != nil {
		object["parentRelations"], err = json.Marshal(a.ParentRelations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parentRelations': %w", err)
		}
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExecuteCommandResponse. Returns the specified
// element and whether it was found
func (a ExecuteCommandResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExecuteCommandResponse
func (a *ExecuteCommandResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExecuteCommandResponse to handle AdditionalProperties
func (a *ExecuteCommandResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["results"]; found {
		err = json.Unmarshal(raw, &a.Results)
		if err != nil {
			return fmt.Errorf("error reading 'results': %w", err)
		}
		delete(object, "results")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExecuteCommandResponse to handle AdditionalProperties
func (a ExecuteCommandResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Results != nil {
		object["results"], err = json.Marshal(a.Results)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'results': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListDevicesResponse. Returns the specified
// element and whether it was found
func (a ListDevicesResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListDevicesResponse
func (a *ListDevicesResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListDevicesResponse to handle AdditionalProperties
func (a *ListDevicesResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["devices"]; found {
		err = json.Unmarshal(raw, &a.Devices)
		if err != nil {
			return fmt.Errorf("error reading 'devices': %w", err)
		}
		delete(object, "devices")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListDevicesResponse to handle AdditionalProperties
func (a ListDevicesResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Devices != nil {
		object["devices"], err = json.Marshal(a.Devices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devices': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListRoomsResponse. Returns the specified
// element and whether it was found
func (a ListRoomsResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListRoomsResponse
func (a *ListRoomsResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListRoomsResponse to handle AdditionalProperties
func (a *ListRoomsResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["rooms"]; found {
		err = json.Unmarshal(raw, &a.Rooms)
		if err != nil {
			return fmt.Errorf("error reading 'rooms': %w", err)
		}
		delete(object, "rooms")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListRoomsResponse to handle AdditionalProperties
func (a ListRoomsResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Rooms != nil {
		object["rooms"], err = json.Marshal(a.Rooms)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rooms': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListStructuresResponse. Returns the specified
// element and whether it was found
func (a ListStructuresResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListStructuresResponse
func (a *ListStructuresResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListStructuresResponse to handle AdditionalProperties
func (a *ListStructuresResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["structures"]; found {
		err = json.Unmarshal(raw, &a.Structures)
		if err != nil {
			return fmt.Errorf("error reading 'structures': %w", err)
		}
		delete(object, "structures")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListStructuresResponse to handle AdditionalProperties
func (a ListStructuresResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Structures != nil {
		object["structures"], err = json.Marshal(a.Structures)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'structures': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ParentRelation. Returns the specified
// element and whether it was found
func (a ParentRelation) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ParentRelation
func (a *ParentRelation) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ParentRelation to handle AdditionalProperties
func (a *ParentRelation) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["displayName"]; found {
		err = json.Unmarshal(raw, &a.DisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'displayName': %w", err)
		}
		delete(object, "displayName")
	}

	if raw, found := object["parent"]; found {
		err = json.Unmarshal(raw, &a.Parent)
		if err != nil {
			return fmt.Errorf("error reading 'parent': %w", err)
		}
		delete(object, "parent")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ParentRelation to handle AdditionalProperties
func (a ParentRelation) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DisplayName != nil {
		object["displayName"], err = json.Marshal(a.DisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'displayName': %w", err)
		}
	}

	if a.Parent != nil {
		object["parent"], err = json.Marshal(a.Parent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parent': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Room. Returns the specified
// element and whether it was found
func (a Room) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Room
func (a *Room) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Room to handle AdditionalProperties
func (a *Room) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Room to handle AdditionalProperties
func (a Room) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Structure. Returns the specified
// element and whether it was found
func (a Structure) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Structure
func (a *Structure) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Structure to handle AdditionalProperties
func (a *Structure) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Structure to handle AdditionalProperties
func (a Structure) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
