// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.

package dependencymodels

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
)

const (
	SdmBearerAuthScopes = "sdmBearerAuth.Scopes"
)

// CameraEventImageGenerateImageRequest Request for CameraEventImage.GenerateImage.
type CameraEventImageGenerateImageRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for CameraEventImage.GenerateImage.
	Params CameraEventImageGenerateImageParams `json:"params"`
}

// CameraLiveStreamExtendRtspStreamRequest Request for CameraLiveStream.ExtendRtspStream.
type CameraLiveStreamExtendRtspStreamRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for CameraLiveStream.ExtendRtspStream.
	Params CameraLiveStreamExtendRtspStreamParams `json:"params"`
}

// CameraLiveStreamExtendWebRtcStreamRequest Request for CameraLiveStream.ExtendWebRtcStream.
type CameraLiveStreamExtendWebRtcStreamRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for CameraLiveStream.ExtendWebRtcStream.
	Params CameraLiveStreamExtendWebRtcStreamParams `json:"params"`
}

// CameraLiveStreamGenerateRtspStreamRequest Request for CameraLiveStream.GenerateRtspStream.
type CameraLiveStreamGenerateRtspStreamRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for CameraLiveStream.GenerateRtspStream.
	Params CameraLiveStreamGenerateRtspStreamParams `json:"params"`
}

// CameraLiveStreamGenerateWebRtcStreamRequest Request for CameraLiveStream.GenerateWebRtcStream.
type CameraLiveStreamGenerateWebRtcStreamRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for CameraLiveStream.GenerateWebRtcStream.
	Params CameraLiveStreamGenerateWebRtcStreamParams `json:"params"`
}

// CameraLiveStreamStopRtspStreamRequest Request for CameraLiveStream.StopRtspStream.
type CameraLiveStreamStopRtspStreamRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for CameraLiveStream.StopRtspStream.
	Params CameraLiveStreamStopRtspStreamParams `json:"params"`
}

// CameraLiveStreamStopWebRtcStreamRequest Request for CameraLiveStream.StopWebRtcStream.
type CameraLiveStreamStopWebRtcStreamRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for CameraLiveStream.StopWebRtcStream.
	Params CameraLiveStreamStopWebRtcStreamParams `json:"params"`
}

// Device defines model for Device.
type Device struct {
	Assignee        *string           `json:"assignee,omitempty"`
	Name            string            `json:"name"`
	ParentRelations *[]ParentRelation `json:"parentRelations,omitempty"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits *Traits `json:"traits,omitempty"`

	// Type Informational device type; use traits to infer capabilities.
	Type                 *DeviceType                `json:"type,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// DeviceType Informational device type; use traits to infer capabilities.
type DeviceType string

// ExecuteCommandRequest Select a command variant to see its required parameters. Examples are sanitized synthetic illustrations of the published SDM contracts. Future command names have an explicit open branch; known commands must use their matching parameter schema.
type ExecuteCommandRequest struct {
	// Command Fully qualified command name. The selected request variant determines the allowed params.
	Command CommandName `json:"command"`

	// Params Parameters are defined by the selected command variant below.
	Params json.RawMessage `json:"params"`
	union  json.RawMessage
}

// ExecuteCommandResponse Command-specific result object. Select the response example with the same command name as the request. Empty acknowledgement schemas overlap, so results use anyOf.
type ExecuteCommandResponse struct {
	Results              *json.RawMessage           `json:"results,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// FanSetTimerRequest Request for Fan.SetTimer.
type FanSetTimerRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for Fan.SetTimer.
	Params FanSetTimerParams `json:"params"`
}

// FutureCommandRequest Compatibility shape for a future command absent from this catalog. Its parameters are caller defined; this branch does not permit malformed parameters for the known commands.
type FutureCommandRequest struct {
	Command CommandName                `json:"command"`
	Params  map[string]json.RawMessage `json:"params"`
}

// ListDevicesResponse defines model for ListDevicesResponse.
type ListDevicesResponse struct {
	Devices              *[]Device                  `json:"devices,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ListRoomsResponse defines model for ListRoomsResponse.
type ListRoomsResponse struct {
	Rooms                *[]Room                    `json:"rooms,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ListStructuresResponse defines model for ListStructuresResponse.
type ListStructuresResponse struct {
	Structures           *[]Structure               `json:"structures,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ParentRelation defines model for ParentRelation.
type ParentRelation struct {
	DisplayName          *string                    `json:"displayName,omitempty"`
	Parent               *string                    `json:"parent,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Room defines model for Room.
type Room struct {
	Name string `json:"name"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits               *Traits                    `json:"traits,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Structure defines model for Structure.
type Structure struct {
	Name string `json:"name"`

	// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
	Traits               *Traits                    `json:"traits,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ThermostatEcoSetModeRequest Request for ThermostatEco.SetMode.
type ThermostatEcoSetModeRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for ThermostatEco.SetMode.
	Params ThermostatEcoSetModeParams `json:"params"`
}

// ThermostatModeSetModeRequest Request for ThermostatMode.SetMode.
type ThermostatModeSetModeRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for ThermostatMode.SetMode.
	Params ThermostatModeSetModeParams `json:"params"`
}

// ThermostatTemperatureSetpointSetCoolRequest Request for ThermostatTemperatureSetpoint.SetCool.
type ThermostatTemperatureSetpointSetCoolRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for ThermostatTemperatureSetpoint.SetCool.
	Params ThermostatTemperatureSetpointSetCoolParams `json:"params"`
}

// ThermostatTemperatureSetpointSetHeatRequest Request for ThermostatTemperatureSetpoint.SetHeat.
type ThermostatTemperatureSetpointSetHeatRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for ThermostatTemperatureSetpoint.SetHeat.
	Params ThermostatTemperatureSetpointSetHeatParams `json:"params"`
}

// ThermostatTemperatureSetpointSetRangeRequest Request for ThermostatTemperatureSetpoint.SetRange.
type ThermostatTemperatureSetpointSetRangeRequest struct {
	Command CommandName `json:"command"`

	// Params Inputs for ThermostatTemperatureSetpoint.SetRange.
	Params ThermostatTemperatureSetpointSetRangeParams `json:"params"`
}

// ListDevicesParams defines parameters for ListDevices.
type ListDevicesParams struct {
	// Filter Optional device custom-name substring filter, for example customName=Living.
	Filter *string `form:"filter,omitempty" json:"filter,omitempty"`
}

// ExecuteCommandJSONRequestBody defines body for ExecuteCommand for application/json ContentType.
type ExecuteCommandJSONRequestBody = ExecuteCommandRequest

// Getter for additional properties for Device. Returns the specified
// element and whether it was found
func (a Device) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Device
func (a *Device) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a *Device) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["assignee"]; found {
		err = json.Unmarshal(raw, &a.Assignee)
		if err != nil {
			return fmt.Errorf("error reading 'assignee': %w", err)
		}
		delete(object, "assignee")
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["parentRelations"]; found {
		err = json.Unmarshal(raw, &a.ParentRelations)
		if err != nil {
			return fmt.Errorf("error reading 'parentRelations': %w", err)
		}
		delete(object, "parentRelations")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Device to handle AdditionalProperties
func (a Device) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Assignee != nil {
		object["assignee"], err = json.Marshal(a.Assignee)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'assignee': %w", err)
		}
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.ParentRelations != nil {
		object["parentRelations"], err = json.Marshal(a.ParentRelations)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parentRelations': %w", err)
		}
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	if a.Type != nil {
		object["type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ExecuteCommandResponse. Returns the specified
// element and whether it was found
func (a ExecuteCommandResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ExecuteCommandResponse
func (a *ExecuteCommandResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ExecuteCommandResponse to handle AdditionalProperties
func (a *ExecuteCommandResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["results"]; found {
		err = json.Unmarshal(raw, &a.Results)
		if err != nil {
			return fmt.Errorf("error reading 'results': %w", err)
		}
		delete(object, "results")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ExecuteCommandResponse to handle AdditionalProperties
func (a ExecuteCommandResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Results != nil {
		object["results"], err = json.Marshal(a.Results)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'results': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListDevicesResponse. Returns the specified
// element and whether it was found
func (a ListDevicesResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListDevicesResponse
func (a *ListDevicesResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListDevicesResponse to handle AdditionalProperties
func (a *ListDevicesResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["devices"]; found {
		err = json.Unmarshal(raw, &a.Devices)
		if err != nil {
			return fmt.Errorf("error reading 'devices': %w", err)
		}
		delete(object, "devices")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListDevicesResponse to handle AdditionalProperties
func (a ListDevicesResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Devices != nil {
		object["devices"], err = json.Marshal(a.Devices)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'devices': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListRoomsResponse. Returns the specified
// element and whether it was found
func (a ListRoomsResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListRoomsResponse
func (a *ListRoomsResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListRoomsResponse to handle AdditionalProperties
func (a *ListRoomsResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["rooms"]; found {
		err = json.Unmarshal(raw, &a.Rooms)
		if err != nil {
			return fmt.Errorf("error reading 'rooms': %w", err)
		}
		delete(object, "rooms")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListRoomsResponse to handle AdditionalProperties
func (a ListRoomsResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Rooms != nil {
		object["rooms"], err = json.Marshal(a.Rooms)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'rooms': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ListStructuresResponse. Returns the specified
// element and whether it was found
func (a ListStructuresResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ListStructuresResponse
func (a *ListStructuresResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ListStructuresResponse to handle AdditionalProperties
func (a *ListStructuresResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["structures"]; found {
		err = json.Unmarshal(raw, &a.Structures)
		if err != nil {
			return fmt.Errorf("error reading 'structures': %w", err)
		}
		delete(object, "structures")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ListStructuresResponse to handle AdditionalProperties
func (a ListStructuresResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Structures != nil {
		object["structures"], err = json.Marshal(a.Structures)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'structures': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ParentRelation. Returns the specified
// element and whether it was found
func (a ParentRelation) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ParentRelation
func (a *ParentRelation) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ParentRelation to handle AdditionalProperties
func (a *ParentRelation) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["displayName"]; found {
		err = json.Unmarshal(raw, &a.DisplayName)
		if err != nil {
			return fmt.Errorf("error reading 'displayName': %w", err)
		}
		delete(object, "displayName")
	}

	if raw, found := object["parent"]; found {
		err = json.Unmarshal(raw, &a.Parent)
		if err != nil {
			return fmt.Errorf("error reading 'parent': %w", err)
		}
		delete(object, "parent")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ParentRelation to handle AdditionalProperties
func (a ParentRelation) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DisplayName != nil {
		object["displayName"], err = json.Marshal(a.DisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'displayName': %w", err)
		}
	}

	if a.Parent != nil {
		object["parent"], err = json.Marshal(a.Parent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'parent': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Room. Returns the specified
// element and whether it was found
func (a Room) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Room
func (a *Room) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Room to handle AdditionalProperties
func (a *Room) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Room to handle AdditionalProperties
func (a Room) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Structure. Returns the specified
// element and whether it was found
func (a Structure) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Structure
func (a *Structure) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Structure to handle AdditionalProperties
func (a *Structure) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["traits"]; found {
		err = json.Unmarshal(raw, &a.Traits)
		if err != nil {
			return fmt.Errorf("error reading 'traits': %w", err)
		}
		delete(object, "traits")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Structure to handle AdditionalProperties
func (a Structure) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	if a.Traits != nil {
		object["traits"], err = json.Marshal(a.Traits)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'traits': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsFanSetTimerRequest returns the union data inside the ExecuteCommandRequest as a FanSetTimerRequest
func (t ExecuteCommandRequest) AsFanSetTimerRequest() (FanSetTimerRequest, error) {
	var body FanSetTimerRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromFanSetTimerRequest overwrites any union data inside the ExecuteCommandRequest as the provided FanSetTimerRequest
func (t *ExecuteCommandRequest) FromFanSetTimerRequest(v FanSetTimerRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeFanSetTimerRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided FanSetTimerRequest
func (t *ExecuteCommandRequest) MergeFanSetTimerRequest(v FanSetTimerRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsThermostatEcoSetModeRequest returns the union data inside the ExecuteCommandRequest as a ThermostatEcoSetModeRequest
func (t ExecuteCommandRequest) AsThermostatEcoSetModeRequest() (ThermostatEcoSetModeRequest, error) {
	var body ThermostatEcoSetModeRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromThermostatEcoSetModeRequest overwrites any union data inside the ExecuteCommandRequest as the provided ThermostatEcoSetModeRequest
func (t *ExecuteCommandRequest) FromThermostatEcoSetModeRequest(v ThermostatEcoSetModeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeThermostatEcoSetModeRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided ThermostatEcoSetModeRequest
func (t *ExecuteCommandRequest) MergeThermostatEcoSetModeRequest(v ThermostatEcoSetModeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsThermostatModeSetModeRequest returns the union data inside the ExecuteCommandRequest as a ThermostatModeSetModeRequest
func (t ExecuteCommandRequest) AsThermostatModeSetModeRequest() (ThermostatModeSetModeRequest, error) {
	var body ThermostatModeSetModeRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromThermostatModeSetModeRequest overwrites any union data inside the ExecuteCommandRequest as the provided ThermostatModeSetModeRequest
func (t *ExecuteCommandRequest) FromThermostatModeSetModeRequest(v ThermostatModeSetModeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeThermostatModeSetModeRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided ThermostatModeSetModeRequest
func (t *ExecuteCommandRequest) MergeThermostatModeSetModeRequest(v ThermostatModeSetModeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsThermostatTemperatureSetpointSetHeatRequest returns the union data inside the ExecuteCommandRequest as a ThermostatTemperatureSetpointSetHeatRequest
func (t ExecuteCommandRequest) AsThermostatTemperatureSetpointSetHeatRequest() (ThermostatTemperatureSetpointSetHeatRequest, error) {
	var body ThermostatTemperatureSetpointSetHeatRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromThermostatTemperatureSetpointSetHeatRequest overwrites any union data inside the ExecuteCommandRequest as the provided ThermostatTemperatureSetpointSetHeatRequest
func (t *ExecuteCommandRequest) FromThermostatTemperatureSetpointSetHeatRequest(v ThermostatTemperatureSetpointSetHeatRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeThermostatTemperatureSetpointSetHeatRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided ThermostatTemperatureSetpointSetHeatRequest
func (t *ExecuteCommandRequest) MergeThermostatTemperatureSetpointSetHeatRequest(v ThermostatTemperatureSetpointSetHeatRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsThermostatTemperatureSetpointSetCoolRequest returns the union data inside the ExecuteCommandRequest as a ThermostatTemperatureSetpointSetCoolRequest
func (t ExecuteCommandRequest) AsThermostatTemperatureSetpointSetCoolRequest() (ThermostatTemperatureSetpointSetCoolRequest, error) {
	var body ThermostatTemperatureSetpointSetCoolRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromThermostatTemperatureSetpointSetCoolRequest overwrites any union data inside the ExecuteCommandRequest as the provided ThermostatTemperatureSetpointSetCoolRequest
func (t *ExecuteCommandRequest) FromThermostatTemperatureSetpointSetCoolRequest(v ThermostatTemperatureSetpointSetCoolRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeThermostatTemperatureSetpointSetCoolRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided ThermostatTemperatureSetpointSetCoolRequest
func (t *ExecuteCommandRequest) MergeThermostatTemperatureSetpointSetCoolRequest(v ThermostatTemperatureSetpointSetCoolRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsThermostatTemperatureSetpointSetRangeRequest returns the union data inside the ExecuteCommandRequest as a ThermostatTemperatureSetpointSetRangeRequest
func (t ExecuteCommandRequest) AsThermostatTemperatureSetpointSetRangeRequest() (ThermostatTemperatureSetpointSetRangeRequest, error) {
	var body ThermostatTemperatureSetpointSetRangeRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromThermostatTemperatureSetpointSetRangeRequest overwrites any union data inside the ExecuteCommandRequest as the provided ThermostatTemperatureSetpointSetRangeRequest
func (t *ExecuteCommandRequest) FromThermostatTemperatureSetpointSetRangeRequest(v ThermostatTemperatureSetpointSetRangeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeThermostatTemperatureSetpointSetRangeRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided ThermostatTemperatureSetpointSetRangeRequest
func (t *ExecuteCommandRequest) MergeThermostatTemperatureSetpointSetRangeRequest(v ThermostatTemperatureSetpointSetRangeRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsCameraEventImageGenerateImageRequest returns the union data inside the ExecuteCommandRequest as a CameraEventImageGenerateImageRequest
func (t ExecuteCommandRequest) AsCameraEventImageGenerateImageRequest() (CameraEventImageGenerateImageRequest, error) {
	var body CameraEventImageGenerateImageRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromCameraEventImageGenerateImageRequest overwrites any union data inside the ExecuteCommandRequest as the provided CameraEventImageGenerateImageRequest
func (t *ExecuteCommandRequest) FromCameraEventImageGenerateImageRequest(v CameraEventImageGenerateImageRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeCameraEventImageGenerateImageRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided CameraEventImageGenerateImageRequest
func (t *ExecuteCommandRequest) MergeCameraEventImageGenerateImageRequest(v CameraEventImageGenerateImageRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsCameraLiveStreamGenerateRtspStreamRequest returns the union data inside the ExecuteCommandRequest as a CameraLiveStreamGenerateRtspStreamRequest
func (t ExecuteCommandRequest) AsCameraLiveStreamGenerateRtspStreamRequest() (CameraLiveStreamGenerateRtspStreamRequest, error) {
	var body CameraLiveStreamGenerateRtspStreamRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromCameraLiveStreamGenerateRtspStreamRequest overwrites any union data inside the ExecuteCommandRequest as the provided CameraLiveStreamGenerateRtspStreamRequest
func (t *ExecuteCommandRequest) FromCameraLiveStreamGenerateRtspStreamRequest(v CameraLiveStreamGenerateRtspStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeCameraLiveStreamGenerateRtspStreamRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided CameraLiveStreamGenerateRtspStreamRequest
func (t *ExecuteCommandRequest) MergeCameraLiveStreamGenerateRtspStreamRequest(v CameraLiveStreamGenerateRtspStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsCameraLiveStreamExtendRtspStreamRequest returns the union data inside the ExecuteCommandRequest as a CameraLiveStreamExtendRtspStreamRequest
func (t ExecuteCommandRequest) AsCameraLiveStreamExtendRtspStreamRequest() (CameraLiveStreamExtendRtspStreamRequest, error) {
	var body CameraLiveStreamExtendRtspStreamRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromCameraLiveStreamExtendRtspStreamRequest overwrites any union data inside the ExecuteCommandRequest as the provided CameraLiveStreamExtendRtspStreamRequest
func (t *ExecuteCommandRequest) FromCameraLiveStreamExtendRtspStreamRequest(v CameraLiveStreamExtendRtspStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeCameraLiveStreamExtendRtspStreamRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided CameraLiveStreamExtendRtspStreamRequest
func (t *ExecuteCommandRequest) MergeCameraLiveStreamExtendRtspStreamRequest(v CameraLiveStreamExtendRtspStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsCameraLiveStreamStopRtspStreamRequest returns the union data inside the ExecuteCommandRequest as a CameraLiveStreamStopRtspStreamRequest
func (t ExecuteCommandRequest) AsCameraLiveStreamStopRtspStreamRequest() (CameraLiveStreamStopRtspStreamRequest, error) {
	var body CameraLiveStreamStopRtspStreamRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromCameraLiveStreamStopRtspStreamRequest overwrites any union data inside the ExecuteCommandRequest as the provided CameraLiveStreamStopRtspStreamRequest
func (t *ExecuteCommandRequest) FromCameraLiveStreamStopRtspStreamRequest(v CameraLiveStreamStopRtspStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeCameraLiveStreamStopRtspStreamRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided CameraLiveStreamStopRtspStreamRequest
func (t *ExecuteCommandRequest) MergeCameraLiveStreamStopRtspStreamRequest(v CameraLiveStreamStopRtspStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsCameraLiveStreamGenerateWebRtcStreamRequest returns the union data inside the ExecuteCommandRequest as a CameraLiveStreamGenerateWebRtcStreamRequest
func (t ExecuteCommandRequest) AsCameraLiveStreamGenerateWebRtcStreamRequest() (CameraLiveStreamGenerateWebRtcStreamRequest, error) {
	var body CameraLiveStreamGenerateWebRtcStreamRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromCameraLiveStreamGenerateWebRtcStreamRequest overwrites any union data inside the ExecuteCommandRequest as the provided CameraLiveStreamGenerateWebRtcStreamRequest
func (t *ExecuteCommandRequest) FromCameraLiveStreamGenerateWebRtcStreamRequest(v CameraLiveStreamGenerateWebRtcStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeCameraLiveStreamGenerateWebRtcStreamRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided CameraLiveStreamGenerateWebRtcStreamRequest
func (t *ExecuteCommandRequest) MergeCameraLiveStreamGenerateWebRtcStreamRequest(v CameraLiveStreamGenerateWebRtcStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsCameraLiveStreamExtendWebRtcStreamRequest returns the union data inside the ExecuteCommandRequest as a CameraLiveStreamExtendWebRtcStreamRequest
func (t ExecuteCommandRequest) AsCameraLiveStreamExtendWebRtcStreamRequest() (CameraLiveStreamExtendWebRtcStreamRequest, error) {
	var body CameraLiveStreamExtendWebRtcStreamRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromCameraLiveStreamExtendWebRtcStreamRequest overwrites any union data inside the ExecuteCommandRequest as the provided CameraLiveStreamExtendWebRtcStreamRequest
func (t *ExecuteCommandRequest) FromCameraLiveStreamExtendWebRtcStreamRequest(v CameraLiveStreamExtendWebRtcStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeCameraLiveStreamExtendWebRtcStreamRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided CameraLiveStreamExtendWebRtcStreamRequest
func (t *ExecuteCommandRequest) MergeCameraLiveStreamExtendWebRtcStreamRequest(v CameraLiveStreamExtendWebRtcStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsCameraLiveStreamStopWebRtcStreamRequest returns the union data inside the ExecuteCommandRequest as a CameraLiveStreamStopWebRtcStreamRequest
func (t ExecuteCommandRequest) AsCameraLiveStreamStopWebRtcStreamRequest() (CameraLiveStreamStopWebRtcStreamRequest, error) {
	var body CameraLiveStreamStopWebRtcStreamRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromCameraLiveStreamStopWebRtcStreamRequest overwrites any union data inside the ExecuteCommandRequest as the provided CameraLiveStreamStopWebRtcStreamRequest
func (t *ExecuteCommandRequest) FromCameraLiveStreamStopWebRtcStreamRequest(v CameraLiveStreamStopWebRtcStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeCameraLiveStreamStopWebRtcStreamRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided CameraLiveStreamStopWebRtcStreamRequest
func (t *ExecuteCommandRequest) MergeCameraLiveStreamStopWebRtcStreamRequest(v CameraLiveStreamStopWebRtcStreamRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

// AsFutureCommandRequest returns the union data inside the ExecuteCommandRequest as a FutureCommandRequest
func (t ExecuteCommandRequest) AsFutureCommandRequest() (FutureCommandRequest, error) {
	var body FutureCommandRequest
	encoded, err := t.MarshalJSON()
	if err != nil {
		return body, err
	}
	err = json.Unmarshal(encoded, &body)
	return body, err
}

// FromFutureCommandRequest overwrites any union data inside the ExecuteCommandRequest as the provided FutureCommandRequest
func (t *ExecuteCommandRequest) FromFutureCommandRequest(v FutureCommandRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(b)
}

// MergeFutureCommandRequest performs a merge with any union data inside the ExecuteCommandRequest, using the provided FutureCommandRequest
func (t *ExecuteCommandRequest) MergeFutureCommandRequest(v FutureCommandRequest) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	current, err := t.MarshalJSON()
	if err != nil {
		return err
	}
	merged, err := runtime.JSONMerge(current, b)
	if err != nil {
		return err
	}
	return t.UnmarshalJSON(merged)
}

func (t ExecuteCommandRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	object["command"], err = json.Marshal(t.Command)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'command': %w", err)
	}

	object["params"], err = json.Marshal(t.Params)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'params': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *ExecuteCommandRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["command"]; found {
		err = json.Unmarshal(raw, &t.Command)
		if err != nil {
			return fmt.Errorf("error reading 'command': %w", err)
		}
	}

	if raw, found := object["params"]; found {
		err = json.Unmarshal(raw, &t.Params)
		if err != nil {
			return fmt.Errorf("error reading 'params': %w", err)
		}
	}

	return err
}
