// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
)

// GoogleError defines model for GoogleError.
type GoogleError struct {
	Code    *int                 `json:"code,omitempty"`
	Details *[]GoogleErrorDetail `json:"details,omitempty"`
	Message *string              `json:"message,omitempty"`

	// Status Open Google RPC status identifier; unknown future statuses remain available.
	Status               *GoogleErrorStatus         `json:"status,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// GoogleErrorDetail Extensible provider error detail. The @type URL identifies its provider-defined payload. Unknown fields remain unchanged.
type GoogleErrorDetail struct {
	Type                 *string                    `json:"@type,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// GoogleErrorResponse defines model for GoogleErrorResponse.
type GoogleErrorResponse struct {
	Error                GoogleError                `json:"error"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// GoogleErrorStatus Open Google RPC status identifier; unknown future statuses remain available.
type GoogleErrorStatus string

// Getter for additional properties for GoogleError. Returns the specified
// element and whether it was found
func (a GoogleError) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GoogleError
func (a *GoogleError) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GoogleError to handle AdditionalProperties
func (a *GoogleError) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["code"]; found {
		err = json.Unmarshal(raw, &a.Code)
		if err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["details"]; found {
		err = json.Unmarshal(raw, &a.Details)
		if err != nil {
			return fmt.Errorf("error reading 'details': %w", err)
		}
		delete(object, "details")
	}

	if raw, found := object["message"]; found {
		err = json.Unmarshal(raw, &a.Message)
		if err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GoogleError to handle AdditionalProperties
func (a GoogleError) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Code != nil {
		object["code"], err = json.Marshal(a.Code)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'code': %w", err)
		}
	}

	if a.Details != nil {
		object["details"], err = json.Marshal(a.Details)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'details': %w", err)
		}
	}

	if a.Message != nil {
		object["message"], err = json.Marshal(a.Message)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'message': %w", err)
		}
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for GoogleErrorDetail. Returns the specified
// element and whether it was found
func (a GoogleErrorDetail) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GoogleErrorDetail
func (a *GoogleErrorDetail) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GoogleErrorDetail to handle AdditionalProperties
func (a *GoogleErrorDetail) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["@type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading '@type': %w", err)
		}
		delete(object, "@type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GoogleErrorDetail to handle AdditionalProperties
func (a GoogleErrorDetail) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Type != nil {
		object["@type"], err = json.Marshal(a.Type)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '@type': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for GoogleErrorResponse. Returns the specified
// element and whether it was found
func (a GoogleErrorResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for GoogleErrorResponse
func (a *GoogleErrorResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for GoogleErrorResponse to handle AdditionalProperties
func (a *GoogleErrorResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for GoogleErrorResponse to handle AdditionalProperties
func (a GoogleErrorResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
