// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.

package dependencymodels

import (
	"encoding/json"
	"fmt"
)

// Defines values for OAuthGrantType.
const (
	AuthorizationCode OAuthGrantType = "authorization_code"
	RefreshToken      OAuthGrantType = "refresh_token"
)

// OAuthErrorCode Open OAuth token error code.
type OAuthErrorCode string

// OAuthErrorResponse defines model for OAuthErrorResponse.
type OAuthErrorResponse struct {
	// Error Open OAuth token error code.
	Error                OAuthErrorCode             `json:"error"`
	ErrorDescription     *string                    `json:"error_description,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// OAuthGrantType defines model for OAuthGrantType.
type OAuthGrantType string

// OAuthTokenRequest defines model for OAuthTokenRequest.
type OAuthTokenRequest struct {
	ClientId     string  `json:"client_id"`
	ClientSecret string  `json:"client_secret"`
	Code         *string `json:"code,omitempty"`

	// CodeVerifier PKCE verifier matching the authorization challenge.
	CodeVerifier *string        `json:"code_verifier,omitempty"`
	GrantType    OAuthGrantType `json:"grant_type"`
	RedirectUri  *string        `json:"redirect_uri,omitempty"`
	RefreshToken *string        `json:"refresh_token,omitempty"`
}

// OAuthTokenResponse defines model for OAuthTokenResponse.
type OAuthTokenResponse struct {
	AccessToken  string  `json:"access_token"`
	ExpiresIn    int     `json:"expires_in"`
	IdToken      *string `json:"id_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`

	// RefreshTokenExpiresIn Nonnegative remaining refresh token lifetime in seconds, returned for time-based access grants.
	RefreshTokenExpiresIn *int                       `json:"refresh_token_expires_in,omitempty"`
	Scope                 *string                    `json:"scope,omitempty"`
	TokenType             string                     `json:"token_type"`
	AdditionalProperties  map[string]json.RawMessage `json:"-"`
}

// OAuthTokenFormdataRequestBody defines body for OAuthToken for application/x-www-form-urlencoded ContentType.
type OAuthTokenFormdataRequestBody = OAuthTokenRequest

// Getter for additional properties for OAuthErrorResponse. Returns the specified
// element and whether it was found
func (a OAuthErrorResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OAuthErrorResponse
func (a *OAuthErrorResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OAuthErrorResponse to handle AdditionalProperties
func (a *OAuthErrorResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["error"]; found {
		err = json.Unmarshal(raw, &a.Error)
		if err != nil {
			return fmt.Errorf("error reading 'error': %w", err)
		}
		delete(object, "error")
	}

	if raw, found := object["error_description"]; found {
		err = json.Unmarshal(raw, &a.ErrorDescription)
		if err != nil {
			return fmt.Errorf("error reading 'error_description': %w", err)
		}
		delete(object, "error_description")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OAuthErrorResponse to handle AdditionalProperties
func (a OAuthErrorResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["error"], err = json.Marshal(a.Error)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'error': %w", err)
	}

	if a.ErrorDescription != nil {
		object["error_description"], err = json.Marshal(a.ErrorDescription)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'error_description': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for OAuthTokenResponse. Returns the specified
// element and whether it was found
func (a OAuthTokenResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for OAuthTokenResponse
func (a *OAuthTokenResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for OAuthTokenResponse to handle AdditionalProperties
func (a *OAuthTokenResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		err = json.Unmarshal(raw, &a.AccessToken)
		if err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["expires_in"]; found {
		err = json.Unmarshal(raw, &a.ExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'expires_in': %w", err)
		}
		delete(object, "expires_in")
	}

	if raw, found := object["id_token"]; found {
		err = json.Unmarshal(raw, &a.IdToken)
		if err != nil {
			return fmt.Errorf("error reading 'id_token': %w", err)
		}
		delete(object, "id_token")
	}

	if raw, found := object["refresh_token"]; found {
		err = json.Unmarshal(raw, &a.RefreshToken)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if raw, found := object["refresh_token_expires_in"]; found {
		err = json.Unmarshal(raw, &a.RefreshTokenExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'refresh_token_expires_in': %w", err)
		}
		delete(object, "refresh_token_expires_in")
	}

	if raw, found := object["scope"]; found {
		err = json.Unmarshal(raw, &a.Scope)
		if err != nil {
			return fmt.Errorf("error reading 'scope': %w", err)
		}
		delete(object, "scope")
	}

	if raw, found := object["token_type"]; found {
		err = json.Unmarshal(raw, &a.TokenType)
		if err != nil {
			return fmt.Errorf("error reading 'token_type': %w", err)
		}
		delete(object, "token_type")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for OAuthTokenResponse to handle AdditionalProperties
func (a OAuthTokenResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["access_token"], err = json.Marshal(a.AccessToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
	}

	object["expires_in"], err = json.Marshal(a.ExpiresIn)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'expires_in': %w", err)
	}

	if a.IdToken != nil {
		object["id_token"], err = json.Marshal(a.IdToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id_token': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refresh_token"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
		}
	}

	if a.RefreshTokenExpiresIn != nil {
		object["refresh_token_expires_in"], err = json.Marshal(a.RefreshTokenExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token_expires_in': %w", err)
		}
	}

	if a.Scope != nil {
		object["scope"], err = json.Marshal(a.Scope)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'scope': %w", err)
		}
	}

	object["token_type"], err = json.Marshal(a.TokenType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token_type': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
