// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
	"time"
)

// AcknowledgeRequest defines model for AcknowledgeRequest.
type AcknowledgeRequest struct {
	AckIds []string `json:"ackIds"`
}

// EmptyResponse defines model for EmptyResponse.
type EmptyResponse map[string]json.RawMessage

// ModifyAckDeadlineRequest defines model for ModifyAckDeadlineRequest.
type ModifyAckDeadlineRequest struct {
	// AckDeadlineSeconds Seconds from 0 through 600; zero makes the message available for immediate redelivery.
	AckDeadlineSeconds int      `json:"ackDeadlineSeconds"`
	AckIds             []string `json:"ackIds"`
}

// PubSubMessage defines model for PubSubMessage.
type PubSubMessage struct {
	Attributes           *map[string]string         `json:"attributes,omitempty"`
	Data                 *[]byte                    `json:"data,omitempty"`
	MessageId            *string                    `json:"messageId,omitempty"`
	OrderingKey          *string                    `json:"orderingKey,omitempty"`
	PublishTime          *time.Time                 `json:"publishTime,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// PullRequest defines model for PullRequest.
type PullRequest struct {
	MaxMessages int `json:"maxMessages"`
	// Deprecated:
	ReturnImmediately *bool `json:"returnImmediately,omitempty"`
}

// PullResponse defines model for PullResponse.
type PullResponse struct {
	ReceivedMessages     *[]ReceivedMessage         `json:"receivedMessages,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// PushEnvelope defines model for PushEnvelope.
type PushEnvelope struct {
	DeliveryAttempt      *int                       `json:"deliveryAttempt,omitempty"`
	Message              PubSubMessage              `json:"message"`
	Subscription         string                     `json:"subscription"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ReceivedMessage defines model for ReceivedMessage.
type ReceivedMessage struct {
	AckId                *string                    `json:"ackId,omitempty"`
	DeliveryAttempt      *int                       `json:"deliveryAttempt,omitempty"`
	Message              *PubSubMessage             `json:"message,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// AcknowledgeJSONRequestBody defines body for Acknowledge for application/json ContentType.
type AcknowledgeJSONRequestBody = AcknowledgeRequest

// ModifyAckDeadlineJSONRequestBody defines body for ModifyAckDeadline for application/json ContentType.
type ModifyAckDeadlineJSONRequestBody = ModifyAckDeadlineRequest

// PullJSONRequestBody defines body for Pull for application/json ContentType.
type PullJSONRequestBody = PullRequest

// Getter for additional properties for PubSubMessage. Returns the specified
// element and whether it was found
func (a PubSubMessage) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PubSubMessage
func (a *PubSubMessage) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PubSubMessage to handle AdditionalProperties
func (a *PubSubMessage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["attributes"]; found {
		err = json.Unmarshal(raw, &a.Attributes)
		if err != nil {
			return fmt.Errorf("error reading 'attributes': %w", err)
		}
		delete(object, "attributes")
	}

	if raw, found := object["data"]; found {
		err = json.Unmarshal(raw, &a.Data)
		if err != nil {
			return fmt.Errorf("error reading 'data': %w", err)
		}
		delete(object, "data")
	}

	if raw, found := object["messageId"]; found {
		err = json.Unmarshal(raw, &a.MessageId)
		if err != nil {
			return fmt.Errorf("error reading 'messageId': %w", err)
		}
		delete(object, "messageId")
	}

	if raw, found := object["orderingKey"]; found {
		err = json.Unmarshal(raw, &a.OrderingKey)
		if err != nil {
			return fmt.Errorf("error reading 'orderingKey': %w", err)
		}
		delete(object, "orderingKey")
	}

	if raw, found := object["publishTime"]; found {
		err = json.Unmarshal(raw, &a.PublishTime)
		if err != nil {
			return fmt.Errorf("error reading 'publishTime': %w", err)
		}
		delete(object, "publishTime")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PubSubMessage to handle AdditionalProperties
func (a PubSubMessage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Attributes != nil {
		object["attributes"], err = json.Marshal(a.Attributes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'attributes': %w", err)
		}
	}

	if a.Data != nil {
		object["data"], err = json.Marshal(a.Data)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'data': %w", err)
		}
	}

	if a.MessageId != nil {
		object["messageId"], err = json.Marshal(a.MessageId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'messageId': %w", err)
		}
	}

	if a.OrderingKey != nil {
		object["orderingKey"], err = json.Marshal(a.OrderingKey)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'orderingKey': %w", err)
		}
	}

	if a.PublishTime != nil {
		object["publishTime"], err = json.Marshal(a.PublishTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'publishTime': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for PullResponse. Returns the specified
// element and whether it was found
func (a PullResponse) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PullResponse
func (a *PullResponse) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PullResponse to handle AdditionalProperties
func (a *PullResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["receivedMessages"]; found {
		err = json.Unmarshal(raw, &a.ReceivedMessages)
		if err != nil {
			return fmt.Errorf("error reading 'receivedMessages': %w", err)
		}
		delete(object, "receivedMessages")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PullResponse to handle AdditionalProperties
func (a PullResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ReceivedMessages != nil {
		object["receivedMessages"], err = json.Marshal(a.ReceivedMessages)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'receivedMessages': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for PushEnvelope. Returns the specified
// element and whether it was found
func (a PushEnvelope) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for PushEnvelope
func (a *PushEnvelope) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for PushEnvelope to handle AdditionalProperties
func (a *PushEnvelope) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["deliveryAttempt"]; found {
		err = json.Unmarshal(raw, &a.DeliveryAttempt)
		if err != nil {
			return fmt.Errorf("error reading 'deliveryAttempt': %w", err)
		}
		delete(object, "deliveryAttempt")
	}

	if raw, found := object["message"]; found {
		err = json.Unmarshal(raw, &a.Message)
		if err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if raw, found := object["subscription"]; found {
		err = json.Unmarshal(raw, &a.Subscription)
		if err != nil {
			return fmt.Errorf("error reading 'subscription': %w", err)
		}
		delete(object, "subscription")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for PushEnvelope to handle AdditionalProperties
func (a PushEnvelope) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DeliveryAttempt != nil {
		object["deliveryAttempt"], err = json.Marshal(a.DeliveryAttempt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deliveryAttempt': %w", err)
		}
	}

	object["message"], err = json.Marshal(a.Message)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'message': %w", err)
	}

	object["subscription"], err = json.Marshal(a.Subscription)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'subscription': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ReceivedMessage. Returns the specified
// element and whether it was found
func (a ReceivedMessage) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ReceivedMessage
func (a *ReceivedMessage) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ReceivedMessage to handle AdditionalProperties
func (a *ReceivedMessage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ackId"]; found {
		err = json.Unmarshal(raw, &a.AckId)
		if err != nil {
			return fmt.Errorf("error reading 'ackId': %w", err)
		}
		delete(object, "ackId")
	}

	if raw, found := object["deliveryAttempt"]; found {
		err = json.Unmarshal(raw, &a.DeliveryAttempt)
		if err != nil {
			return fmt.Errorf("error reading 'deliveryAttempt': %w", err)
		}
		delete(object, "deliveryAttempt")
	}

	if raw, found := object["message"]; found {
		err = json.Unmarshal(raw, &a.Message)
		if err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ReceivedMessage to handle AdditionalProperties
func (a ReceivedMessage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AckId != nil {
		object["ackId"], err = json.Marshal(a.AckId)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ackId': %w", err)
		}
	}

	if a.DeliveryAttempt != nil {
		object["deliveryAttempt"], err = json.Marshal(a.DeliveryAttempt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deliveryAttempt': %w", err)
		}
	}

	if a.Message != nil {
		object["message"], err = json.Marshal(a.Message)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'message': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
