// Package dependencymodels provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package dependencymodels

import (
	"encoding/json"
	"fmt"
	"time"
)

// AudioCodec Known values; incoming values remain open for future service additions.
type AudioCodec = string

// CameraClipPreview Presence-aware CameraClipPreview trait fields; event updates may contain only changed fields. Unknown fields are retained.
type CameraClipPreview map[string]json.RawMessage

// CameraEventImage Presence-aware CameraEventImage trait fields; event updates may contain only changed fields. Unknown fields are retained.
type CameraEventImage map[string]json.RawMessage

// CameraImage Presence-aware CameraImage trait fields; event updates may contain only changed fields. Unknown fields are retained.
type CameraImage struct {
	MaxImageResolution   *ImageResolution           `json:"maxImageResolution,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CameraLiveStream Presence-aware CameraLiveStream trait fields; event updates may contain only changed fields. Unknown fields are retained.
type CameraLiveStream struct {
	AudioCodecs          *[]AudioCodec              `json:"audioCodecs,omitempty"`
	MaxVideoResolution   *VideoResolution           `json:"maxVideoResolution,omitempty"`
	SupportedProtocols   *[]StreamProtocol          `json:"supportedProtocols,omitempty"`
	VideoCodecs          *[]VideoCodec              `json:"videoCodecs,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// CameraMotion Presence-aware CameraMotion trait fields; event updates may contain only changed fields. Unknown fields are retained.
type CameraMotion map[string]json.RawMessage

// CameraPerson Presence-aware CameraPerson trait fields; event updates may contain only changed fields. Unknown fields are retained.
type CameraPerson map[string]json.RawMessage

// CameraSound Presence-aware CameraSound trait fields; event updates may contain only changed fields. Unknown fields are retained.
type CameraSound map[string]json.RawMessage

// Connectivity Presence-aware Connectivity trait fields; event updates may contain only changed fields. Unknown fields are retained.
type Connectivity struct {
	// Status Known values; incoming values remain open for future service additions.
	Status               *ConnectivityStatus        `json:"status,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ConnectivityStatus Known values; incoming values remain open for future service additions.
type ConnectivityStatus = string

// DoorbellChime Presence-aware DoorbellChime trait fields; event updates may contain only changed fields. Unknown fields are retained.
type DoorbellChime map[string]json.RawMessage

// EcoMode Known values; incoming values remain open for future service additions.
type EcoMode = string

// Fan Presence-aware Fan trait fields; event updates may contain only changed fields. Unknown fields are retained.
type Fan struct {
	// TimerMode Known values; incoming values remain open for future service additions.
	TimerMode            *FanTimerMode              `json:"timerMode,omitempty"`
	TimerTimeout         *time.Time                 `json:"timerTimeout,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// FanTimerMode Known values; incoming values remain open for future service additions.
type FanTimerMode = string

// Humidity Presence-aware Humidity trait fields; event updates may contain only changed fields. Unknown fields are retained.
type Humidity struct {
	// AmbientHumidityPercent Ambient relative humidity percent.
	AmbientHumidityPercent *float64                   `json:"ambientHumidityPercent,omitempty"`
	AdditionalProperties   map[string]json.RawMessage `json:"-"`
}

// HvacStatus Known values; incoming values remain open for future service additions.
type HvacStatus = string

// ImageResolution defines model for ImageResolution.
type ImageResolution struct {
	// Height Maximum image height in pixels.
	Height *int32 `json:"height,omitempty"`

	// Width Maximum image width in pixels.
	Width                *int32                     `json:"width,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Info Presence-aware Info trait fields; event updates may contain only changed fields. Unknown fields are retained.
type Info struct {
	CustomName           *string                    `json:"customName,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// RoomInfo Presence-aware RoomInfo trait fields; event updates may contain only changed fields. Unknown fields are retained.
type RoomInfo struct {
	CustomName           *string                    `json:"customName,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Settings Presence-aware Settings trait fields; event updates may contain only changed fields. Unknown fields are retained.
type Settings struct {
	// TemperatureScale Known values; incoming values remain open for future service additions.
	TemperatureScale     *TemperatureScale          `json:"temperatureScale,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// StreamProtocol Known values; incoming values remain open for future service additions.
type StreamProtocol = string

// StructureInfo Presence-aware StructureInfo trait fields; event updates may contain only changed fields. Unknown fields are retained.
type StructureInfo struct {
	CustomName           *string                    `json:"customName,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Temperature Presence-aware Temperature trait fields; event updates may contain only changed fields. Unknown fields are retained.
type Temperature struct {
	// AmbientTemperatureCelsius Ambient temperature in degrees Celsius.
	AmbientTemperatureCelsius *float64                   `json:"ambientTemperatureCelsius,omitempty"`
	AdditionalProperties      map[string]json.RawMessage `json:"-"`
}

// TemperatureScale Known values; incoming values remain open for future service additions.
type TemperatureScale = string

// ThermostatEco Presence-aware ThermostatEco trait fields; event updates may contain only changed fields. Unknown fields are retained.
type ThermostatEco struct {
	AvailableModes *[]EcoMode `json:"availableModes,omitempty"`
	CoolCelsius    *float64   `json:"coolCelsius,omitempty"`
	HeatCelsius    *float64   `json:"heatCelsius,omitempty"`

	// Mode Known values; incoming values remain open for future service additions.
	Mode                 *EcoMode                   `json:"mode,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ThermostatHvac Presence-aware ThermostatHvac trait fields; event updates may contain only changed fields. Unknown fields are retained.
type ThermostatHvac struct {
	// Status Known values; incoming values remain open for future service additions.
	Status               *HvacStatus                `json:"status,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ThermostatMode Presence-aware ThermostatMode trait fields; event updates may contain only changed fields. Unknown fields are retained.
type ThermostatMode struct {
	AvailableModes *[]ThermostatModeValue `json:"availableModes,omitempty"`

	// Mode Known values; incoming values remain open for future service additions.
	Mode                 *ThermostatModeValue       `json:"mode,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// ThermostatModeValue Known values; incoming values remain open for future service additions.
type ThermostatModeValue = string

// ThermostatTemperatureSetpoint Presence-aware ThermostatTemperatureSetpoint trait fields; event updates may contain only changed fields. Unknown fields are retained.
type ThermostatTemperatureSetpoint struct {
	CoolCelsius          *float64                   `json:"coolCelsius,omitempty"`
	HeatCelsius          *float64                   `json:"heatCelsius,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Traits Known trait keys with capability-marker presence and unknown future trait values preserved.
type Traits struct {
	// SdmDevicesTraitsCameraClipPreview Presence-aware CameraClipPreview trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsCameraClipPreview *CameraClipPreview `json:"sdm.devices.traits.CameraClipPreview,omitempty"`

	// SdmDevicesTraitsCameraEventImage Presence-aware CameraEventImage trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsCameraEventImage *CameraEventImage `json:"sdm.devices.traits.CameraEventImage,omitempty"`

	// SdmDevicesTraitsCameraImage Presence-aware CameraImage trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsCameraImage *CameraImage `json:"sdm.devices.traits.CameraImage,omitempty"`

	// SdmDevicesTraitsCameraLiveStream Presence-aware CameraLiveStream trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsCameraLiveStream *CameraLiveStream `json:"sdm.devices.traits.CameraLiveStream,omitempty"`

	// SdmDevicesTraitsCameraMotion Presence-aware CameraMotion trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsCameraMotion *CameraMotion `json:"sdm.devices.traits.CameraMotion,omitempty"`

	// SdmDevicesTraitsCameraPerson Presence-aware CameraPerson trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsCameraPerson *CameraPerson `json:"sdm.devices.traits.CameraPerson,omitempty"`

	// SdmDevicesTraitsCameraSound Presence-aware CameraSound trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsCameraSound *CameraSound `json:"sdm.devices.traits.CameraSound,omitempty"`

	// SdmDevicesTraitsConnectivity Presence-aware Connectivity trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsConnectivity *Connectivity `json:"sdm.devices.traits.Connectivity,omitempty"`

	// SdmDevicesTraitsDoorbellChime Presence-aware DoorbellChime trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsDoorbellChime *DoorbellChime `json:"sdm.devices.traits.DoorbellChime,omitempty"`

	// SdmDevicesTraitsFan Presence-aware Fan trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsFan *Fan `json:"sdm.devices.traits.Fan,omitempty"`

	// SdmDevicesTraitsHumidity Presence-aware Humidity trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsHumidity *Humidity `json:"sdm.devices.traits.Humidity,omitempty"`

	// SdmDevicesTraitsInfo Presence-aware Info trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsInfo *Info `json:"sdm.devices.traits.Info,omitempty"`

	// SdmDevicesTraitsSettings Presence-aware Settings trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsSettings *Settings `json:"sdm.devices.traits.Settings,omitempty"`

	// SdmDevicesTraitsTemperature Presence-aware Temperature trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsTemperature *Temperature `json:"sdm.devices.traits.Temperature,omitempty"`

	// SdmDevicesTraitsThermostatEco Presence-aware ThermostatEco trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsThermostatEco *ThermostatEco `json:"sdm.devices.traits.ThermostatEco,omitempty"`

	// SdmDevicesTraitsThermostatHvac Presence-aware ThermostatHvac trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsThermostatHvac *ThermostatHvac `json:"sdm.devices.traits.ThermostatHvac,omitempty"`

	// SdmDevicesTraitsThermostatMode Presence-aware ThermostatMode trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsThermostatMode *ThermostatMode `json:"sdm.devices.traits.ThermostatMode,omitempty"`

	// SdmDevicesTraitsThermostatTemperatureSetpoint Presence-aware ThermostatTemperatureSetpoint trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmDevicesTraitsThermostatTemperatureSetpoint *ThermostatTemperatureSetpoint `json:"sdm.devices.traits.ThermostatTemperatureSetpoint,omitempty"`

	// SdmStructuresTraitsInfo Presence-aware StructureInfo trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmStructuresTraitsInfo *StructureInfo `json:"sdm.structures.traits.Info,omitempty"`

	// SdmStructuresTraitsRoomInfo Presence-aware RoomInfo trait fields; event updates may contain only changed fields. Unknown fields are retained.
	SdmStructuresTraitsRoomInfo *RoomInfo                  `json:"sdm.structures.traits.RoomInfo,omitempty"`
	AdditionalProperties        map[string]json.RawMessage `json:"-"`
}

// VideoCodec Known values; incoming values remain open for future service additions.
type VideoCodec = string

// VideoResolution defines model for VideoResolution.
type VideoResolution struct {
	// Height Maximum video height in pixels.
	Height *int32 `json:"height,omitempty"`

	// Width Maximum video width in pixels.
	Width                *int32                     `json:"width,omitempty"`
	AdditionalProperties map[string]json.RawMessage `json:"-"`
}

// Getter for additional properties for CameraImage. Returns the specified
// element and whether it was found
func (a CameraImage) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CameraImage
func (a *CameraImage) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CameraImage to handle AdditionalProperties
func (a *CameraImage) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["maxImageResolution"]; found {
		err = json.Unmarshal(raw, &a.MaxImageResolution)
		if err != nil {
			return fmt.Errorf("error reading 'maxImageResolution': %w", err)
		}
		delete(object, "maxImageResolution")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CameraImage to handle AdditionalProperties
func (a CameraImage) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.MaxImageResolution != nil {
		object["maxImageResolution"], err = json.Marshal(a.MaxImageResolution)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'maxImageResolution': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for CameraLiveStream. Returns the specified
// element and whether it was found
func (a CameraLiveStream) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for CameraLiveStream
func (a *CameraLiveStream) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for CameraLiveStream to handle AdditionalProperties
func (a *CameraLiveStream) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["audioCodecs"]; found {
		err = json.Unmarshal(raw, &a.AudioCodecs)
		if err != nil {
			return fmt.Errorf("error reading 'audioCodecs': %w", err)
		}
		delete(object, "audioCodecs")
	}

	if raw, found := object["maxVideoResolution"]; found {
		err = json.Unmarshal(raw, &a.MaxVideoResolution)
		if err != nil {
			return fmt.Errorf("error reading 'maxVideoResolution': %w", err)
		}
		delete(object, "maxVideoResolution")
	}

	if raw, found := object["supportedProtocols"]; found {
		err = json.Unmarshal(raw, &a.SupportedProtocols)
		if err != nil {
			return fmt.Errorf("error reading 'supportedProtocols': %w", err)
		}
		delete(object, "supportedProtocols")
	}

	if raw, found := object["videoCodecs"]; found {
		err = json.Unmarshal(raw, &a.VideoCodecs)
		if err != nil {
			return fmt.Errorf("error reading 'videoCodecs': %w", err)
		}
		delete(object, "videoCodecs")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for CameraLiveStream to handle AdditionalProperties
func (a CameraLiveStream) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AudioCodecs != nil {
		object["audioCodecs"], err = json.Marshal(a.AudioCodecs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'audioCodecs': %w", err)
		}
	}

	if a.MaxVideoResolution != nil {
		object["maxVideoResolution"], err = json.Marshal(a.MaxVideoResolution)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'maxVideoResolution': %w", err)
		}
	}

	if a.SupportedProtocols != nil {
		object["supportedProtocols"], err = json.Marshal(a.SupportedProtocols)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'supportedProtocols': %w", err)
		}
	}

	if a.VideoCodecs != nil {
		object["videoCodecs"], err = json.Marshal(a.VideoCodecs)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'videoCodecs': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Connectivity. Returns the specified
// element and whether it was found
func (a Connectivity) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Connectivity
func (a *Connectivity) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Connectivity to handle AdditionalProperties
func (a *Connectivity) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Connectivity to handle AdditionalProperties
func (a Connectivity) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Fan. Returns the specified
// element and whether it was found
func (a Fan) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Fan
func (a *Fan) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Fan to handle AdditionalProperties
func (a *Fan) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["timerMode"]; found {
		err = json.Unmarshal(raw, &a.TimerMode)
		if err != nil {
			return fmt.Errorf("error reading 'timerMode': %w", err)
		}
		delete(object, "timerMode")
	}

	if raw, found := object["timerTimeout"]; found {
		err = json.Unmarshal(raw, &a.TimerTimeout)
		if err != nil {
			return fmt.Errorf("error reading 'timerTimeout': %w", err)
		}
		delete(object, "timerTimeout")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Fan to handle AdditionalProperties
func (a Fan) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.TimerMode != nil {
		object["timerMode"], err = json.Marshal(a.TimerMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timerMode': %w", err)
		}
	}

	if a.TimerTimeout != nil {
		object["timerTimeout"], err = json.Marshal(a.TimerTimeout)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timerTimeout': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Humidity. Returns the specified
// element and whether it was found
func (a Humidity) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Humidity
func (a *Humidity) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Humidity to handle AdditionalProperties
func (a *Humidity) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ambientHumidityPercent"]; found {
		err = json.Unmarshal(raw, &a.AmbientHumidityPercent)
		if err != nil {
			return fmt.Errorf("error reading 'ambientHumidityPercent': %w", err)
		}
		delete(object, "ambientHumidityPercent")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Humidity to handle AdditionalProperties
func (a Humidity) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AmbientHumidityPercent != nil {
		object["ambientHumidityPercent"], err = json.Marshal(a.AmbientHumidityPercent)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ambientHumidityPercent': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ImageResolution. Returns the specified
// element and whether it was found
func (a ImageResolution) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ImageResolution
func (a *ImageResolution) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ImageResolution to handle AdditionalProperties
func (a *ImageResolution) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["height"]; found {
		err = json.Unmarshal(raw, &a.Height)
		if err != nil {
			return fmt.Errorf("error reading 'height': %w", err)
		}
		delete(object, "height")
	}

	if raw, found := object["width"]; found {
		err = json.Unmarshal(raw, &a.Width)
		if err != nil {
			return fmt.Errorf("error reading 'width': %w", err)
		}
		delete(object, "width")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ImageResolution to handle AdditionalProperties
func (a ImageResolution) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Height != nil {
		object["height"], err = json.Marshal(a.Height)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'height': %w", err)
		}
	}

	if a.Width != nil {
		object["width"], err = json.Marshal(a.Width)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'width': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Info. Returns the specified
// element and whether it was found
func (a Info) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Info
func (a *Info) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Info to handle AdditionalProperties
func (a *Info) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["customName"]; found {
		err = json.Unmarshal(raw, &a.CustomName)
		if err != nil {
			return fmt.Errorf("error reading 'customName': %w", err)
		}
		delete(object, "customName")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Info to handle AdditionalProperties
func (a Info) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CustomName != nil {
		object["customName"], err = json.Marshal(a.CustomName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'customName': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for RoomInfo. Returns the specified
// element and whether it was found
func (a RoomInfo) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for RoomInfo
func (a *RoomInfo) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for RoomInfo to handle AdditionalProperties
func (a *RoomInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["customName"]; found {
		err = json.Unmarshal(raw, &a.CustomName)
		if err != nil {
			return fmt.Errorf("error reading 'customName': %w", err)
		}
		delete(object, "customName")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for RoomInfo to handle AdditionalProperties
func (a RoomInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CustomName != nil {
		object["customName"], err = json.Marshal(a.CustomName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'customName': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Settings. Returns the specified
// element and whether it was found
func (a Settings) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Settings
func (a *Settings) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Settings to handle AdditionalProperties
func (a *Settings) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["temperatureScale"]; found {
		err = json.Unmarshal(raw, &a.TemperatureScale)
		if err != nil {
			return fmt.Errorf("error reading 'temperatureScale': %w", err)
		}
		delete(object, "temperatureScale")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Settings to handle AdditionalProperties
func (a Settings) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.TemperatureScale != nil {
		object["temperatureScale"], err = json.Marshal(a.TemperatureScale)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'temperatureScale': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for StructureInfo. Returns the specified
// element and whether it was found
func (a StructureInfo) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StructureInfo
func (a *StructureInfo) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StructureInfo to handle AdditionalProperties
func (a *StructureInfo) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["customName"]; found {
		err = json.Unmarshal(raw, &a.CustomName)
		if err != nil {
			return fmt.Errorf("error reading 'customName': %w", err)
		}
		delete(object, "customName")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StructureInfo to handle AdditionalProperties
func (a StructureInfo) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CustomName != nil {
		object["customName"], err = json.Marshal(a.CustomName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'customName': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Temperature. Returns the specified
// element and whether it was found
func (a Temperature) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Temperature
func (a *Temperature) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Temperature to handle AdditionalProperties
func (a *Temperature) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["ambientTemperatureCelsius"]; found {
		err = json.Unmarshal(raw, &a.AmbientTemperatureCelsius)
		if err != nil {
			return fmt.Errorf("error reading 'ambientTemperatureCelsius': %w", err)
		}
		delete(object, "ambientTemperatureCelsius")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Temperature to handle AdditionalProperties
func (a Temperature) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AmbientTemperatureCelsius != nil {
		object["ambientTemperatureCelsius"], err = json.Marshal(a.AmbientTemperatureCelsius)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ambientTemperatureCelsius': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ThermostatEco. Returns the specified
// element and whether it was found
func (a ThermostatEco) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ThermostatEco
func (a *ThermostatEco) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ThermostatEco to handle AdditionalProperties
func (a *ThermostatEco) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["availableModes"]; found {
		err = json.Unmarshal(raw, &a.AvailableModes)
		if err != nil {
			return fmt.Errorf("error reading 'availableModes': %w", err)
		}
		delete(object, "availableModes")
	}

	if raw, found := object["coolCelsius"]; found {
		err = json.Unmarshal(raw, &a.CoolCelsius)
		if err != nil {
			return fmt.Errorf("error reading 'coolCelsius': %w", err)
		}
		delete(object, "coolCelsius")
	}

	if raw, found := object["heatCelsius"]; found {
		err = json.Unmarshal(raw, &a.HeatCelsius)
		if err != nil {
			return fmt.Errorf("error reading 'heatCelsius': %w", err)
		}
		delete(object, "heatCelsius")
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &a.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
		delete(object, "mode")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ThermostatEco to handle AdditionalProperties
func (a ThermostatEco) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AvailableModes != nil {
		object["availableModes"], err = json.Marshal(a.AvailableModes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'availableModes': %w", err)
		}
	}

	if a.CoolCelsius != nil {
		object["coolCelsius"], err = json.Marshal(a.CoolCelsius)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'coolCelsius': %w", err)
		}
	}

	if a.HeatCelsius != nil {
		object["heatCelsius"], err = json.Marshal(a.HeatCelsius)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'heatCelsius': %w", err)
		}
	}

	if a.Mode != nil {
		object["mode"], err = json.Marshal(a.Mode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mode': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ThermostatHvac. Returns the specified
// element and whether it was found
func (a ThermostatHvac) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ThermostatHvac
func (a *ThermostatHvac) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ThermostatHvac to handle AdditionalProperties
func (a *ThermostatHvac) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ThermostatHvac to handle AdditionalProperties
func (a ThermostatHvac) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ThermostatMode. Returns the specified
// element and whether it was found
func (a ThermostatMode) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ThermostatMode
func (a *ThermostatMode) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ThermostatMode to handle AdditionalProperties
func (a *ThermostatMode) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["availableModes"]; found {
		err = json.Unmarshal(raw, &a.AvailableModes)
		if err != nil {
			return fmt.Errorf("error reading 'availableModes': %w", err)
		}
		delete(object, "availableModes")
	}

	if raw, found := object["mode"]; found {
		err = json.Unmarshal(raw, &a.Mode)
		if err != nil {
			return fmt.Errorf("error reading 'mode': %w", err)
		}
		delete(object, "mode")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ThermostatMode to handle AdditionalProperties
func (a ThermostatMode) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.AvailableModes != nil {
		object["availableModes"], err = json.Marshal(a.AvailableModes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'availableModes': %w", err)
		}
	}

	if a.Mode != nil {
		object["mode"], err = json.Marshal(a.Mode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'mode': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for ThermostatTemperatureSetpoint. Returns the specified
// element and whether it was found
func (a ThermostatTemperatureSetpoint) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ThermostatTemperatureSetpoint
func (a *ThermostatTemperatureSetpoint) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ThermostatTemperatureSetpoint to handle AdditionalProperties
func (a *ThermostatTemperatureSetpoint) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["coolCelsius"]; found {
		err = json.Unmarshal(raw, &a.CoolCelsius)
		if err != nil {
			return fmt.Errorf("error reading 'coolCelsius': %w", err)
		}
		delete(object, "coolCelsius")
	}

	if raw, found := object["heatCelsius"]; found {
		err = json.Unmarshal(raw, &a.HeatCelsius)
		if err != nil {
			return fmt.Errorf("error reading 'heatCelsius': %w", err)
		}
		delete(object, "heatCelsius")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ThermostatTemperatureSetpoint to handle AdditionalProperties
func (a ThermostatTemperatureSetpoint) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CoolCelsius != nil {
		object["coolCelsius"], err = json.Marshal(a.CoolCelsius)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'coolCelsius': %w", err)
		}
	}

	if a.HeatCelsius != nil {
		object["heatCelsius"], err = json.Marshal(a.HeatCelsius)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'heatCelsius': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for Traits. Returns the specified
// element and whether it was found
func (a Traits) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for Traits
func (a *Traits) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for Traits to handle AdditionalProperties
func (a *Traits) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["sdm.devices.traits.CameraClipPreview"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsCameraClipPreview)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.CameraClipPreview': %w", err)
		}
		delete(object, "sdm.devices.traits.CameraClipPreview")
	}

	if raw, found := object["sdm.devices.traits.CameraEventImage"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsCameraEventImage)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.CameraEventImage': %w", err)
		}
		delete(object, "sdm.devices.traits.CameraEventImage")
	}

	if raw, found := object["sdm.devices.traits.CameraImage"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsCameraImage)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.CameraImage': %w", err)
		}
		delete(object, "sdm.devices.traits.CameraImage")
	}

	if raw, found := object["sdm.devices.traits.CameraLiveStream"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsCameraLiveStream)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.CameraLiveStream': %w", err)
		}
		delete(object, "sdm.devices.traits.CameraLiveStream")
	}

	if raw, found := object["sdm.devices.traits.CameraMotion"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsCameraMotion)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.CameraMotion': %w", err)
		}
		delete(object, "sdm.devices.traits.CameraMotion")
	}

	if raw, found := object["sdm.devices.traits.CameraPerson"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsCameraPerson)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.CameraPerson': %w", err)
		}
		delete(object, "sdm.devices.traits.CameraPerson")
	}

	if raw, found := object["sdm.devices.traits.CameraSound"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsCameraSound)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.CameraSound': %w", err)
		}
		delete(object, "sdm.devices.traits.CameraSound")
	}

	if raw, found := object["sdm.devices.traits.Connectivity"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsConnectivity)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.Connectivity': %w", err)
		}
		delete(object, "sdm.devices.traits.Connectivity")
	}

	if raw, found := object["sdm.devices.traits.DoorbellChime"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsDoorbellChime)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.DoorbellChime': %w", err)
		}
		delete(object, "sdm.devices.traits.DoorbellChime")
	}

	if raw, found := object["sdm.devices.traits.Fan"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsFan)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.Fan': %w", err)
		}
		delete(object, "sdm.devices.traits.Fan")
	}

	if raw, found := object["sdm.devices.traits.Humidity"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsHumidity)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.Humidity': %w", err)
		}
		delete(object, "sdm.devices.traits.Humidity")
	}

	if raw, found := object["sdm.devices.traits.Info"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsInfo)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.Info': %w", err)
		}
		delete(object, "sdm.devices.traits.Info")
	}

	if raw, found := object["sdm.devices.traits.Settings"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsSettings)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.Settings': %w", err)
		}
		delete(object, "sdm.devices.traits.Settings")
	}

	if raw, found := object["sdm.devices.traits.Temperature"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsTemperature)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.Temperature': %w", err)
		}
		delete(object, "sdm.devices.traits.Temperature")
	}

	if raw, found := object["sdm.devices.traits.ThermostatEco"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsThermostatEco)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.ThermostatEco': %w", err)
		}
		delete(object, "sdm.devices.traits.ThermostatEco")
	}

	if raw, found := object["sdm.devices.traits.ThermostatHvac"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsThermostatHvac)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.ThermostatHvac': %w", err)
		}
		delete(object, "sdm.devices.traits.ThermostatHvac")
	}

	if raw, found := object["sdm.devices.traits.ThermostatMode"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsThermostatMode)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.ThermostatMode': %w", err)
		}
		delete(object, "sdm.devices.traits.ThermostatMode")
	}

	if raw, found := object["sdm.devices.traits.ThermostatTemperatureSetpoint"]; found {
		err = json.Unmarshal(raw, &a.SdmDevicesTraitsThermostatTemperatureSetpoint)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.devices.traits.ThermostatTemperatureSetpoint': %w", err)
		}
		delete(object, "sdm.devices.traits.ThermostatTemperatureSetpoint")
	}

	if raw, found := object["sdm.structures.traits.Info"]; found {
		err = json.Unmarshal(raw, &a.SdmStructuresTraitsInfo)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.structures.traits.Info': %w", err)
		}
		delete(object, "sdm.structures.traits.Info")
	}

	if raw, found := object["sdm.structures.traits.RoomInfo"]; found {
		err = json.Unmarshal(raw, &a.SdmStructuresTraitsRoomInfo)
		if err != nil {
			return fmt.Errorf("error reading 'sdm.structures.traits.RoomInfo': %w", err)
		}
		delete(object, "sdm.structures.traits.RoomInfo")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for Traits to handle AdditionalProperties
func (a Traits) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.SdmDevicesTraitsCameraClipPreview != nil {
		object["sdm.devices.traits.CameraClipPreview"], err = json.Marshal(a.SdmDevicesTraitsCameraClipPreview)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.CameraClipPreview': %w", err)
		}
	}

	if a.SdmDevicesTraitsCameraEventImage != nil {
		object["sdm.devices.traits.CameraEventImage"], err = json.Marshal(a.SdmDevicesTraitsCameraEventImage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.CameraEventImage': %w", err)
		}
	}

	if a.SdmDevicesTraitsCameraImage != nil {
		object["sdm.devices.traits.CameraImage"], err = json.Marshal(a.SdmDevicesTraitsCameraImage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.CameraImage': %w", err)
		}
	}

	if a.SdmDevicesTraitsCameraLiveStream != nil {
		object["sdm.devices.traits.CameraLiveStream"], err = json.Marshal(a.SdmDevicesTraitsCameraLiveStream)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.CameraLiveStream': %w", err)
		}
	}

	if a.SdmDevicesTraitsCameraMotion != nil {
		object["sdm.devices.traits.CameraMotion"], err = json.Marshal(a.SdmDevicesTraitsCameraMotion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.CameraMotion': %w", err)
		}
	}

	if a.SdmDevicesTraitsCameraPerson != nil {
		object["sdm.devices.traits.CameraPerson"], err = json.Marshal(a.SdmDevicesTraitsCameraPerson)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.CameraPerson': %w", err)
		}
	}

	if a.SdmDevicesTraitsCameraSound != nil {
		object["sdm.devices.traits.CameraSound"], err = json.Marshal(a.SdmDevicesTraitsCameraSound)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.CameraSound': %w", err)
		}
	}

	if a.SdmDevicesTraitsConnectivity != nil {
		object["sdm.devices.traits.Connectivity"], err = json.Marshal(a.SdmDevicesTraitsConnectivity)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.Connectivity': %w", err)
		}
	}

	if a.SdmDevicesTraitsDoorbellChime != nil {
		object["sdm.devices.traits.DoorbellChime"], err = json.Marshal(a.SdmDevicesTraitsDoorbellChime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.DoorbellChime': %w", err)
		}
	}

	if a.SdmDevicesTraitsFan != nil {
		object["sdm.devices.traits.Fan"], err = json.Marshal(a.SdmDevicesTraitsFan)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.Fan': %w", err)
		}
	}

	if a.SdmDevicesTraitsHumidity != nil {
		object["sdm.devices.traits.Humidity"], err = json.Marshal(a.SdmDevicesTraitsHumidity)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.Humidity': %w", err)
		}
	}

	if a.SdmDevicesTraitsInfo != nil {
		object["sdm.devices.traits.Info"], err = json.Marshal(a.SdmDevicesTraitsInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.Info': %w", err)
		}
	}

	if a.SdmDevicesTraitsSettings != nil {
		object["sdm.devices.traits.Settings"], err = json.Marshal(a.SdmDevicesTraitsSettings)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.Settings': %w", err)
		}
	}

	if a.SdmDevicesTraitsTemperature != nil {
		object["sdm.devices.traits.Temperature"], err = json.Marshal(a.SdmDevicesTraitsTemperature)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.Temperature': %w", err)
		}
	}

	if a.SdmDevicesTraitsThermostatEco != nil {
		object["sdm.devices.traits.ThermostatEco"], err = json.Marshal(a.SdmDevicesTraitsThermostatEco)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.ThermostatEco': %w", err)
		}
	}

	if a.SdmDevicesTraitsThermostatHvac != nil {
		object["sdm.devices.traits.ThermostatHvac"], err = json.Marshal(a.SdmDevicesTraitsThermostatHvac)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.ThermostatHvac': %w", err)
		}
	}

	if a.SdmDevicesTraitsThermostatMode != nil {
		object["sdm.devices.traits.ThermostatMode"], err = json.Marshal(a.SdmDevicesTraitsThermostatMode)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.ThermostatMode': %w", err)
		}
	}

	if a.SdmDevicesTraitsThermostatTemperatureSetpoint != nil {
		object["sdm.devices.traits.ThermostatTemperatureSetpoint"], err = json.Marshal(a.SdmDevicesTraitsThermostatTemperatureSetpoint)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.devices.traits.ThermostatTemperatureSetpoint': %w", err)
		}
	}

	if a.SdmStructuresTraitsInfo != nil {
		object["sdm.structures.traits.Info"], err = json.Marshal(a.SdmStructuresTraitsInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.structures.traits.Info': %w", err)
		}
	}

	if a.SdmStructuresTraitsRoomInfo != nil {
		object["sdm.structures.traits.RoomInfo"], err = json.Marshal(a.SdmStructuresTraitsRoomInfo)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'sdm.structures.traits.RoomInfo': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for VideoResolution. Returns the specified
// element and whether it was found
func (a VideoResolution) Get(fieldName string) (value json.RawMessage, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for VideoResolution
func (a *VideoResolution) Set(fieldName string, value json.RawMessage) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]json.RawMessage)
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for VideoResolution to handle AdditionalProperties
func (a *VideoResolution) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["height"]; found {
		err = json.Unmarshal(raw, &a.Height)
		if err != nil {
			return fmt.Errorf("error reading 'height': %w", err)
		}
		delete(object, "height")
	}

	if raw, found := object["width"]; found {
		err = json.Unmarshal(raw, &a.Width)
		if err != nil {
			return fmt.Errorf("error reading 'width': %w", err)
		}
		delete(object, "width")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]json.RawMessage)
		for fieldName, fieldBuf := range object {
			var fieldVal json.RawMessage
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for VideoResolution to handle AdditionalProperties
func (a VideoResolution) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Height != nil {
		object["height"], err = json.Marshal(a.Height)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'height': %w", err)
		}
	}

	if a.Width != nil {
		object["width"], err = json.Marshal(a.Width)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'width': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
