// Command contractcheck validates named model ownership and handwritten boundaries.
package main

import (
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

var errContract = errors.New("contract verification failed")

func main() {
	output := flag.String("write-inventory", "", "Write a complete generated declaration and source-use inventory")
	flag.Parse()

	err := auditModels(".")
	if err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	if *output != "" {
		err = writeInventory(".", *output)
		if err != nil {
			_, _ = fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}
}

func auditModels(root string) error {
	components, err := loadComponents(root)
	if err != nil {
		return err
	}

	err = filepath.WalkDir(filepath.Join(root, "pkg"), func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return fmt.Errorf("scan models: %w", walkErr)
		}

		if entry.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		return checkModelPath(path, components)
	})
	if err != nil {
		return fmt.Errorf("audit model tree: %w", err)
	}

	return verifyGeneratedFields(root)
}

func checkModelPath(path string, components map[string]bool) error {
	file, err := parser.ParseFile(token.NewFileSet(), path, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("parse model source: %w", err)
	}

	generated := strings.HasSuffix(path, ".gen.go")
	if generated && !registeredGeneratedPath(filepath.ToSlash(path)) {
		return fmt.Errorf("%w: unregistered generated file %s", errContract, path)
	}

	if generated && !hasGeneratorMarker(file) && !constantsOnly(file) {
		return fmt.Errorf("%w: missing generator provenance %s", errContract, path)
	}

	return auditModelFile(file, generated, components, path)
}

func constantsOnly(file *ast.File) bool {
	for _, declaration := range file.Decls {
		group, ok := declaration.(*ast.GenDecl)
		if !ok || group.Tok != token.CONST {
			return false
		}
	}

	return len(file.Decls) > 0
}

func hasGeneratorMarker(file *ast.File) bool {
	for _, group := range file.Comments {
		for _, comment := range group.List {
			if strings.Contains(comment.Text, "Code generated by github.com/oapi-codegen/") ||
				strings.Contains(comment.Text, "Code generated by @asyncapi/modelina") {
				return true
			}
		}
	}

	return false
}

func auditModelFile(file *ast.File, generated bool, components map[string]bool, path string) error {
	var failure error

	ast.Inspect(file, func(node ast.Node) bool {
		if failure != nil {
			return false
		}

		if structure, ok := node.(*ast.StructType); ok && !generated {
			failure = handwrittenStruct(structure, path)
		}

		declaration, ok := node.(*ast.TypeSpec)
		if !ok || !generated || !ast.IsExported(declaration.Name.Name) {
			return true
		}

		if !components[declaration.Name.Name] {
			failure = fmt.Errorf("%w: %s: generated type %s lacks schema owner", errContract, path, declaration.Name.Name)
		}

		return true
	})

	return failure
}

func handwrittenStruct(structure *ast.StructType, path string) error {
	for _, field := range structure.Fields.List {
		if field.Tag == nil {
			continue
		}

		tag, err := strconv.Unquote(field.Tag.Value)
		if err != nil {
			return fmt.Errorf("decode field tag: %w", err)
		}

		if strings.Contains(tag, "json:") {
			return fmt.Errorf("%w: %s: handwritten JSON struct (SCHEMA-16)", errContract, path)
		}
	}

	return nil
}

func registeredGeneratedPath(path string) bool {
	for _, known := range generatedPaths() {
		if path == known || strings.HasSuffix(path, "/"+known) {
			return true
		}
	}

	return false
}

func generatedPaths() []string {
	return []string{
		"pkg/dependencymodels/commands.gen.go",
		"pkg/dependencymodels/device-values.gen.go",
		"pkg/dependencymodels/devices.gen.go",
		"pkg/dependencymodels/events.gen.go",
		"pkg/dependencymodels/error-values.gen.go",
		"pkg/dependencymodels/errors.gen.go",
		"pkg/dependencymodels/oauth.gen.go",
		"pkg/dependencymodels/oauth-values.gen.go",
		"pkg/dependencymodels/pubsub.gen.go",
		"pkg/dependencymodels/trait-values.gen.go",
		"pkg/dependencymodels/traits.gen.go",
		"pkg/sdm/commands.gen.go",
		"pkg/sdm/events.gen.go",
		"pkg/sdm/media.gen.go",
		"pkg/sdm/provider-errors.gen.go",
		"pkg/sdm/resources.gen.go",
		"pkg/sdm/trait-values.gen.go",
		"pkg/sdm/traits.gen.go",
	}
}
