package main

import (
	"fmt"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestModelNegativeControls(t *testing.T) {
	t.Parallel()

	cases := map[string]string{
		"unused exported JSON type": "package probe; type Unused struct { Value string `json:\"novel\"` }",
		"anonymous nested object":   "package probe; type Holder struct { Nested struct { Value string `json:\"novel\"` } }",
		"forged marker": "// Code generated fake DO NOT EDIT.\n" +
			"package probe; type Unused struct { Value string `json:\"novel\"` }",
	}
	for name, source := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			file, err := parser.ParseFile(token.NewFileSet(), "probe.go", source, parser.ParseComments)
			if err != nil {
				t.Fatal(err)
			}

			err = auditModelFile(file, false, map[string]bool{"Known": true}, "probe.go")
			if err == nil {
				t.Fatal("handwritten wire model accepted")
			}
		})
	}
}

func TestRealGeneratedModelMutation(t *testing.T) {
	t.Parallel()
	root := mirrorModelTree(t)
	path := filepath.Join(root, "pkg/dependencymodels/commands.gen.go")

	// #nosec G304 -- path is a copied generated file inside t.TempDir.
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	mutated := strings.Replace(string(data), "type FanSetTimerParams struct {",
		"type FanSetTimerParams struct {\nNovel string `json:\"novel\"`", 1)

	// #nosec G703 -- path is fixed to commands.gen.go inside the test's private temporary tree.
	err = os.WriteFile(path, []byte(mutated), 0o600)
	if err != nil {
		t.Fatal(err)
	}

	err = auditModels(root)
	if err == nil {
		t.Fatal("genuine generated marker with new JSON field accepted")
	}
}

func TestRealForgedGeneratedPath(t *testing.T) {
	t.Parallel()
	root := mirrorModelTree(t)
	path := filepath.Join(root, "pkg/dependencymodels/commands-fake.gen.go")
	source := "// Code generated by github.com/oapi-codegen/oapi-codegen/v2 DO NOT EDIT.\n" +
		"package dependencymodels; type FanSetTimerParamsFake struct { Novel string `json:\"novel\"` }"

	err := os.WriteFile(path, []byte(source), 0o600)
	if err != nil {
		t.Fatal(err)
	}

	err = auditModels(root)
	if err == nil {
		t.Fatal("forged generated file accepted")
	}
}

func mirrorModelTree(t *testing.T) string {
	t.Helper()
	root := t.TempDir()

	for _, tree := range []string{"api", "pkg", "internal"} {
		sourceRoot := filepath.Join("../..", tree)

		err := filepath.WalkDir(sourceRoot, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}

			relative, err := filepath.Rel("../..", path)
			if err != nil {
				return fmt.Errorf("resolve copied path: %w", err)
			}

			destination := filepath.Join(root, relative)
			if entry.IsDir() {
				return os.MkdirAll(destination, 0o750)
			}

			// #nosec G304 G122 -- this read-only walk copies repository source to an isolated test tree.
			data, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("read copied fixture: %w", err)
			}

			// #nosec G703 -- destination is the same walked relative path inside t.TempDir.
			return os.WriteFile(destination, data, 0o600)
		})
		if err != nil {
			t.Fatal(err)
		}
	}

	return root
}

func TestModelOwnership(t *testing.T) {
	t.Parallel()

	file, err := parser.ParseFile(token.NewFileSet(), "probe.gen.go",
		"package probe; type Unregistered struct { Value string }", 0)
	if err != nil {
		t.Fatal(err)
	}

	err = auditModelFile(file, true, map[string]bool{"Known": true}, "probe.gen.go")
	if err == nil {
		t.Fatal("unbound generated model accepted")
	}
}
