// Code generated from checked-in API schemas. DO NOT EDIT.

package protocol

const (
	BasicPrefix                   = "Basic "
	BearerPrefix                  = "Bearer "
	CollectionDevices             = "devices"
	CollectionEnterprises         = "enterprises"
	CollectionProjects            = "projects"
	CollectionRooms               = "rooms"
	CollectionStructures          = "structures"
	CollectionSubscriptions       = "subscriptions"
	FormClientID                  = "client_id"
	FormClientSecret              = "client_secret"
	FormCode                      = "code"
	FormCodeVerifier              = "code_verifier"
	FormGrantType                 = "grant_type"
	FormRedirectURI               = "redirect_uri"
	FormRefreshToken              = "refresh_token"
	HeaderAccept                  = "Accept"
	HeaderAuthorization           = "Authorization"
	HeaderContentType             = "Content-Type"
	HeaderPubSubMessageID         = "x-goog-pubsub-message-id"
	HeaderPubSubOrderingKey       = "x-goog-pubsub-ordering-key"
	HeaderPubSubPublishTime       = "x-goog-pubsub-publish-time"
	HeaderPubSubSubscriptionName  = "x-goog-pubsub-subscription-name"
	HeaderUserID                  = "userId"
	KeyDevices                    = "devices"
	KeyResults                    = "results"
	KeyRooms                      = "rooms"
	KeyStructures                 = "structures"
	MIMEApplicationJSON           = "application/json"
	MIMEFormURLEncoded            = "application/x-www-form-urlencoded"
	MediaClipURLPattern           = "^https://[^/?#]+/"
	MediaImageURLPattern          = "^https://[^/?#]+/sdm_event_snapshot/[^?#]+"
	MethodAcknowledge             = "POST"
	MethodExecuteCommand          = "POST"
	MethodGetDevice               = "GET"
	MethodGetRoom                 = "GET"
	MethodGetStructure            = "GET"
	MethodListDevices             = "GET"
	MethodListRooms               = "GET"
	MethodListStructures          = "GET"
	MethodModifyAckDeadline       = "POST"
	MethodOAuthToken              = "POST"
	MethodPCMConsent              = "GET"
	MethodPull                    = "POST"
	OAuthAccessTypeOffline        = "offline"
	OAuthBaseURL                  = "https://oauth2.googleapis.com"
	OAuthErrorAccessDenied        = "access_denied"
	OAuthErrorInvalidClient       = "invalid_client"
	OAuthErrorInvalidGrant        = "invalid_grant"
	OAuthErrorUnauthorizedClient  = "unauthorized_client"
	OAuthGrantAuthorizationCode   = "authorization_code"
	OAuthGrantRefreshToken        = "refresh_token"
	OAuthPKCES256                 = "S256"
	OAuthPromptConsent            = "consent"
	OAuthResponseTypeCode         = "code"
	OAuthScopeSDM                 = "https://www.googleapis.com/auth/sdm.service"
	PCMBaseURL                    = "https://nestservices.google.com"
	PathAcknowledge               = "/projects/%s/subscriptions/%s:acknowledge"
	PathExecuteCommand            = "/enterprises/%s/devices/%s:executeCommand"
	PathGetDevice                 = "/enterprises/%s/devices/%s"
	PathGetRoom                   = "/enterprises/%s/structures/%s/rooms/%s"
	PathGetStructure              = "/enterprises/%s/structures/%s"
	PathListDevices               = "/enterprises/%s/devices"
	PathListRooms                 = "/enterprises/%s/structures/%s/rooms"
	PathListStructures            = "/enterprises/%s/structures"
	PathModifyAckDeadline         = "/projects/%s/subscriptions/%s:modifyAckDeadline"
	PathOAuthToken                = "/token"
	PathPCMConsent                = "/partnerconnections/%s/auth"
	PathPull                      = "/projects/%s/subscriptions/%s:pull"
	PubSubBaseURL                 = "https://pubsub.googleapis.com/v1"
	QueryFilter                   = "filter"
	QueryHeight                   = "height"
	QueryParamAccessType          = "access_type"
	QueryParamClientID            = "client_id"
	QueryParamCode                = "code"
	QueryParamCodeChallenge       = "code_challenge"
	QueryParamCodeChallengeMethod = "code_challenge_method"
	QueryParamError               = "error"
	QueryParamErrorDescription    = "error_description"
	QueryParamPrompt              = "prompt"
	QueryParamRedirectURI         = "redirect_uri"
	QueryParamResponseType        = "response_type"
	QueryParamScope               = "scope"
	QueryParamState               = "state"
	QueryWidth                    = "width"
	SDMBaseURL                    = "https://smartdevicemanagement.googleapis.com/v1"
	SDPApplicationPrefix          = "m=application "
	SDPAudioPrefix                = "m=audio "
	SDPCarriageReturn             = "\r"
	SDPDirectionSendReceiveLine   = "a=sendrecv"
	SDPInactiveLine               = "a=inactive"
	SDPLineSeparator              = "\n"
	SDPMediaPrefix                = "m="
	SDPMidPrefix                  = "a=mid:"
	SDPOpusCodec                  = "opus/48000"
	SDPReceiveOnlyLine            = "a=recvonly"
	SDPRtpMapPrefix               = "a=rtpmap:"
	SDPSendOnlyLine               = "a=sendonly"
	SDPSessionVersion             = "v=0"
	SDPVideoPrefix                = "m=video "
)
